common.mk, cutlass/gemm/block_task.h, cutlass/util/debug.h
Make CUTLASS compilable with clang and tweak few minor things to enforce inlining where necessary.
=> Clang fixes

README.md, tools/test/perf/testbench_options.h
Updated URL to Doxygen and modified usage statement in test program.
=> Updated URL to Doxygen and modified usage statement 

README.md, tools/test/perf/testbench_options.h
Minor updates to usage and README.
=> Minor updates to usage and README.

README.md, changelog.md
Minor edits to README and changelog pursuant CUTLASS 1.0.1 patch.
=> Minor edits to README and changelog pursuant CUTLASS 1.0.1 patch.

CUTLASS.md
=> Updated CUTLASS.md

README.md
=> Clarification to README

README.md
=> Fixed typeo

CONTRIBUTORS.md, README.md, media/docs/code_organization.md, media/docs/doxygen_mainpage.md, media/docs/gemm_api.md, media/docs/profiler.md, media/docs/programming_guidelines.md, media/docs/quickstart.md
Improved formatting, clarity, and content of several documents..
=> Improved formatting, clarity, and content of several documents.

include/cutlass/matrix_traits.h
Removed redundant conjugation operations from matrix_traits.
=> Removed redundant conjugation operations from matrix_traits.

examples/13_fused_two_gemms/fused_gemm.cu, media/docs/profiler.md, media/docs/quickstart.md
Added examples to enable the unity build when "all" kernels are enabled.
=> Added examples to enable the unity build

PUBLICATIONS.md
=> Create  PUBLICATIONS.md

examples/15_ampere_sparse_tensorop_gemm/ampere_sparse_tensorop_gemm.cu, include/cutlass/conv/kernel/default_conv3d_fprop.h
* add 2stage fprop 3d into default file (#224 )
* fix a broken sparse gemm example (#225 )
=> Fix for issue#224 and issue#225

include/cutlass/epilogue/thread/linear_combination_relu.h
=> Fix for issue #221

include/cutlass/transform/thread/transpose.h
1. Add 'pragma once' preprocess directive
2. Replace prmt PTX with __byte_perm intrinsic
Signed-off-by: Peter Han <fujun.han@iluvatar.ai>
=> tranpose.h update based on issue#233

include/cutlass/epilogue/thread/activation.h, include/cutlass/epilogue/thread/linear_combination_gelu.h, test/unit/epilogue/thread/linear_combination.cu
Fixes to enable Gelu fusion with half
=> Fixes to Gelu for half and fusion

include/cutlass/epilogue/thread/linear_combination_clamp.h, include/cutlass/half.h, include/cutlass/integer_subbyte.h, include/cutlass/numeric_conversion.h, include/cutlass/platform/platform.h
=> Fixes for public issue #265

include/cutlass/transform/threadblock/predicated_tile_iterator.h
Was reading into the codebase and found some typos. 
Please let me know if there're beginner-friendly tasks I can help with.
=> Typo Fixes

include/cutlass/epilogue/threadblock/epilogue_with_reduction.h, include/cutlass/epilogue/threadblock/predicated_tile_iterator.h
Fix the register spill happened in the epilogue.
=> fix epilogue register spill

media/docs/profiler.md, tools/profiler/src/options.cu
cleanup the profiler commandline help message and profiler documentations.
#304
=> Fix profiler cmd doc

media/docs/implicit_gemm_convolution.md
=> fix typo in doc

include/cutlass/arch/wmma_sm70.h, include/cutlass/arch/wmma_sm72.h
=> fix wmma shape typo

CONTRIBUTORS.md
Fixed formatting in CONTRIBUTORS.md file by adding trailing space to force newline.
=> Fixed formatting in CONTRIBUTORS.md file

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/documentation_request.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/submit_question.md, .github/workflows/labeler.yml, .github/workflows/new-issues-to-triage-projects.yml, .github/workflows/stale.yml, README.md
Updated README and added issue templates.
=> Updated README and added issue templates.

tools/library/scripts/gemm_operation.py, tools/library/scripts/generator.py, tools/library/scripts/library.py
=> add the missing pieces of tf32x3 profiler code

include/cutlass/conv/kernel/default_conv2d.h, include/cutlass/conv/kernel/default_conv2d_fprop_with_broadcast.h, include/cutlass/conv/kernel/default_conv2d_fprop_with_reduction.h, test/unit/common/filter_architecture.cpp, test/unit/conv/device/CMakeLists.txt, test/unit/conv/device/conv2d_fprop_with_broadcast_sm70.cu
Enable convolution with fused epilogue for Volta Tensor Cores
=> Enable convolution with fused epilogue for Volta Tensor Cores

examples/16_ampere_tensorop_conv2dfprop/ampere_tensorop_conv2dfprop.cu, include/cutlass/epilogue/thread/activation.h, include/cutlass/epilogue/thread/linear_combination_clamp.h, include/cutlass/epilogue/thread/linear_combination_gelu.h, include/cutlass/epilogue/thread/linear_combination_generic.h, include/cutlass/epilogue/thread/linear_combination_hardswish.h, include/cutlass/epilogue/thread/linear_combination_relu0.h, include/cutlass/epilogue/thread/linear_combination_sigmoid.h, include/cutlass/epilogue/thread/linear_combination_silu.h, include/cutlass/epilogue/threadblock/default_epilogue_tensor_op.h, include/cutlass/functional.h
14% speed up on hardswish fusion
=> [hardswish] correct implmentation

include/cutlass/epilogue/threadblock/shared_load_iterator.h
Signed-off-by: Fujun Han <fujun.han@iluvatar.ai>
=> Remove redundant offset def and init in shared_load_iterator.h

examples/40_cutlass_py/test-cutlass-py.py
Used relative paths for includes in Python example
=> Used relative paths for includes in Python example

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/documentation_request.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/submit_question.md, .github/workflows/labeler.yml, .github/workflows/new-issues-to-triage-projects.yml, .github/workflows/stale.yml
=> add .github

test/unit/conv/device/conv2d_with_reduction_testbed.h
Add device final reduction kernel to conv2d reduction testbed and verify the correctness of the reduction tensor.
=> add verification of the reduction tensor

include/cutlass/gemm/warp/mma_tensor_op_tile_iterator.h
Note: There are other places with similar comments. I didn't check every one of them.
=> Fix a comment about LDSM layout.

include/cutlass/epilogue/thread/linear_combination_generic.h
ref to https://github.com/NVIDIA/cutlass/issues/530
=> fix bugs in linear_combination_generic.h missing some head file

include/cutlass/epilogue/thread/activation.h, include/cutlass/epilogue/thread/linear_combination_leaky_relu.h
add leaky relu to the epilogue elementwise.
=> add leaky relu

include/cutlass/epilogue/thread/activation.h
=> [activation] tanh

include/cutlass/epilogue/thread/linear_combination_leaky_relu.h
epilogue leaky relu support scale type, same as LinearCombinationGeneric
=> epilogue leaky relu support ScaleType

examples/13_two_tensor_op_fusion/kernel/b2b_gemm.h, examples/13_two_tensor_op_fusion/threadblock/b2b_mma_multistage.h, examples/13_two_tensor_op_fusion/threadblock/b2b_mma_multistage_smem_accumulator.h, examples/13_two_tensor_op_fusion/threadblock/b2b_mma_pipelined.h, examples/13_two_tensor_op_fusion/threadblock/b2b_mma_pipelined_smem_accumulator.h, examples/13_two_tensor_op_fusion/threadblock/default_b2b_mma_smem_accumulator.h, include/cutlass/gemm/warp/mma_tensor_op_tile_access_iterator.h, include/cutlass/transform/threadblock/predicated_vector_access_iterator.h
Add residual support for shmem staging iterator used in back-to-back GEMM fusion. This allows support of problem_size_0_n that is not multiple of 32.
@danthe3rd , would you please give it a try?
=> b2b gemm residual

CITATION.cff, tools/util/include/cutlass/util/device_groupnorm.h
=> add two missing files

examples/41_multi_head_attention/fused_multihead_attention.cu
The rationale behind this change is explained in #563
=> Remove excessive includes from examples/41_multi_head_attention

include/cutlass/epilogue/thread/activation.h
- support Identity activation for activation is disable
- bugfix: add CUTLASS_HOST_DEVICE for Sigmoid activation
=> Fix identity sigmoid activation

examples/42_fused_multi_head_attention/kernel_forward.h
=> add `#pragma once` for header file in example 42

examples/41_fused_multi_head_attention/fused_multihead_attention_fixed_seqlen.cu, examples/41_fused_multi_head_attention/fused_multihead_attention_variable_seqlen.cu, examples/41_fused_multi_head_attention/kernel_forward.h
=> minor changes to fmha verification code

include/cutlass/gemm/device/gemm_universal_base.h, include/cutlass/gemm/threadblock/threadblock_swizzle_streamk.h
@mikeiovine 
128x128x32 has occupancy 2, i.e. 2 tb on one SM.  When tile size is bigger or smaller, the occupancy can be 1 or 3.
=> improve streamk load balance when occupancy is 1 or 3

CHANGELOG.md, README.md, examples/47_ampere_gemm_universal_streamk/CMakeLists.txt, examples/47_ampere_gemm_universal_streamk/ampere_gemm_universal_streamk.cu, examples/CMakeLists.txt, examples/common/helper.h, include/cutlass/barrier.h, include/cutlass/gemm/kernel/gemm_universal_streamk.h, include/cutlass/gemm/threadblock/threadblock_swizzle_streamk.h, tools/library/scripts/generator.py
should be the last pr for streamk before tagging 2.11.
streamk should always be faster than not using streamk now.
@antinucleon @ipiszy @mikeiovine @Laurawly
=> streamk example and performance tuning

examples/47_ampere_gemm_universal_streamk/ampere_gemm_universal_streamk.cu
@neoblizz @antinucleon @mikeiovine @ipiszy @@Laurawly
=> streamk paper link in the example

include/cute/int_tuple.hpp
Work around a likely GCC 8.x issue with fold expressions and generic lambdas.
Only use the work-around when the host compiler is GCC 8.x. This avoids any concerns about the work-around possibly hindering inlining for a critical CuTe function (`cute::product`).
Users can experiment with the work-around for other compilers or compiler versions by defining the following macro.
`CUTE_FOLD_GENERIC_LAMBDA_WORKAROUND`
Fixes https://github.com/NVIDIA/cutlass/issues/788
=> Fix 8.4 + CUDA 11.4 build

include/cutlass/epilogue/threadblock/epilogue.h
=> Add acc2smem back to epilogue/threadblock/epilogue.h

include/cutlass/epilogue/threadblock/default_epilogue_tensor_op.h, include/cutlass/epilogue/threadblock/shared_load_iterator_mixed.h, include/cutlass/epilogue/warp/tile_iterator_tensor_op_mixed.h
This needed changes as discussed in
=> Changes to iterators to support s8 gemm with f16 outputs

include/cutlass/gemm/kernel/gemm_universal_streamk.h, include/cutlass/gemm/threadblock/threadblock_swizzle_streamk.h
@terrychenism @danthe3rd @Laurawly
=> streamk fix

PUBLICATIONS.md
updating a publication accepted at IEEE IPDPS'23.
=> add a CUTLASS publication

examples/35_gemm_softmax/gemm_with_softmax.h
Currently, the [`GemmSoftmax`](https://github.com/NVIDIA/cutlass/blob/master/examples/35_gemm_softmax/gemm_with_softmax.h#L579) in [`examples/35_gemm_softmax`](https://github.com/NVIDIA/cutlass/tree/master/examples/35_gemm_softmax) only works with up to 49152 bytes of shared memory. This is problematic, as some of the parameter combinations generated by the [`GenerateSM80`](https://github.com/NVIDIA/cutlass/blob/master/tools/library/scripts/generator.py#L3979) require more shared memory.
This PR suggests setting the `cudaFuncAttributeMaxDynamicSharedMemorySize` to a larger value if required. E.g., if the `kStages = 3` [here](https://github.com/NVIDIA/cutlass/blob/master/examples/35_gemm_softmax/gemm_softmax.cu#L227) in the `gemm_softmax.cu` is increased to 10, the example fails to run …
=> Set larger dynamic shared memory size in GemmSoftmax

tools/library/scripts/generator.py
When channel num is 32, these kernels are more performant
=> Add tile_n=32 and tile_k=32 kernels in generator.py

include/cute/arch/util.hpp
See the commit messages for why I created this PR and what it does.
=> Fix host compilation of cute::cast_smem_ptr_to_uint.

PUBLICATIONS.md
Paper "graphene tensor ir" is highly inspired by cute, by reading this paper we could have a better understanding for the design of cute. so I suggest adding this publication. I thought it could help us much for learning and understanding cute. "Inspiration" is also a kind of "use".
https://dl.acm.org/doi/abs/10.1145/3582016.3582018
=> Add one Publication which is inspired by cutlass

include/cutlass/numeric_conversion.h
=> Fix numeric conversion warning

tools/library/scripts/gemm_operation.py
Some small fixes in python scripts:
* Add simple hash and eq methods to GemmOperation;
* Remove tailing whitespaces in python scripts;
=> Small fixes in python scripts

include/cute/arch/mma_sm90_desc.hpp
closes #1066
cc @thakkarV @mhoemmen
=> fix cinttypes issue with STDC_FORMAT_MACROS

examples/16_ampere_tensorop_conv2dfprop/ampere_tensorop_conv2dfprop.cu, examples/23_ampere_gemm_operand_reduction_fusion/ampere_gemm_operand_reduction_fusion.cu
=> style(examples): typo

examples/13_two_tensor_op_fusion/kernel/b2b_gemm.h, examples/44_multi_gemm_ir_and_codegen/ir_gen/gen_kernel.py, examples/45_dual_gemm/kernel/dual_gemm.h
This fixes compatibility with H100 and resolves #1094
=> Replace 0x1f with 0xffffffff in __shfl_sync

include/cutlass/platform/platform.h
=> Add #include <limits> to platform.h

python/cutlass_library/generator.py
@manishucsd @IonThruster @kerrmudgeon @rhenry-nv
=> fix alignmentC for h16816_s8xf16

include/cutlass/predicate_vector.h
Fix incorrect use of masks in is_zero
=> Fix is_zero

CHANGELOG.md, media/docs/build/building_in_windows_with_visual_studio.md, media/docs/build/building_with_clang_as_host_compiler.md, media/docs/efficient_gemm.md, media/docs/pipeline.md
Fix several broken links in docs.
=> Fix several broken links

include/cute/atom/mma_atom.hpp
=> Qualify calls to make_fragment_? from templated base class.

examples/15_ampere_sparse_tensorop_gemm/CMakeLists.txt, examples/15_ampere_sparse_tensorop_gemm/ampere_sparse_tensorop_gemm_with_visitor.cu, include/cutlass/gemm/device/gemm_sparse_with_visitor.h, include/cutlass/gemm/kernel/default_gemm_sparse_with_visitor.h, include/cutlass/gemm/kernel/params_sparse_base.h, include/cutlass/gemm/kernel/sparse_gemm.h, include/cutlass/gemm/kernel/sparse_gemm_with_visitor.h
=> Add support for sparse GEMM with visitor epilogue

python/cutlass/backend/arguments.py, python/cutlass/backend/conv2d_operation.py, python/cutlass/backend/gemm_operation.py, python/cutlass/backend/reduction_operation.py, python/cutlass/op/conv.py, python/cutlass/op/gemm.py, python/cutlass/op/gemm_grouped.py
Hi there,
I exposed the stream as an option in the python kernel call interfaces. This is needed for my research project at U of I. Please let me know if this could be merged into your main branch with shepherding. 
Thank you.
Best Regards,
Kun
=> expose stream API in python kernel call interfaces

media/docs/profiler.md, tools/library/src/util.cu
Updates profiler arguments as well as the documentation for using the profiler.
=> Profiler docs and Argument Update For Raster Order

include/cutlass/conv/device/conv_universal_adapter.hpp, include/cutlass/gemm/device/gemm_universal_adapter.h
Launch 1x1x1 cluster shape kernels stamped out in #1665 with triple angle bracket launch.
CC @hwu36 @thakkarV @IonThruster
=> 1x1x1 Cluster Shape Kernel Launch

CHANGELOG.md, README.md, test/unit/gemm/device/gemm_f16n_f16t_f16t_tensor_op_f32_sm80.cu, test/unit/gemm/device/gemm_f16n_f16t_f32t_tensor_op_f32_sparse_sm80.cu, test/unit/gemm/device/gemm_f16t_f16n_f32t_tensor_op_f32_sparse_sm80.cu, test/unit/gemm/device/gemm_f32n_f32t_f32t_tensor_op_f32_sparse_sm80.cu, test/unit/gemm/device/gemm_f32t_f32n_f32t_tensor_op_f32_sparse_sm80.cu, test/unit/gemm/device/gemm_s4t_s4n_s32t_tensor_op_s32_sparse_sm80.cu, test/unit/gemm/device/gemm_s8t_s8n_s32t_tensor_op_s32_sparse_sm80.cu, test/unit/gemm/device/multistage_testbed.h, test/unit/gemm/device/syrk_f32n_f32t_tensor_op_fast_f32_sm80.cu, test/unit/gemm/device/syrk_f32t_f32t_tensor_op_fast_f32_sm80.cu, test/unit/gemm/device/syrk_tf32n_f32t_tensor_op_f32_sm80.cu, test/unit/gemm/device/syrk_tf32t_f32t_tensor_op_f32_sm80.cu
update 3.5.1 doc to reflect the enhancement to ampere sparse gemm and conv epilogue.
=> update 3.5.1 readme/changelog

include/cutlass/uint128.h
@mhoemmen @thakkarV 
fix #1571
=> fix uint128

include/cutlass/barrier.h
=> Fix assertion logic in check_barrier_in_range

include/cutlass/epilogue/fusion/operations.hpp, include/cutlass/epilogue/fusion/sm90_callbacks_tma_warpspecialized.hpp
=> Add Sm90LinCombPerColBias

media/docs/cute/0x_gemm_tutorial.md
Fix cute tutorial doc problem.
=> [Doc] Fix cute tutorial doc problem.

examples/55_hopper_mixed_dtype_gemm/55_hopper_int4_bf16_gemm.cu, examples/55_hopper_mixed_dtype_gemm/CMakeLists.txt, examples/55_hopper_mixed_dtype_gemm/packed_scale.hpp, examples/55_hopper_mixed_dtype_gemm/reorder_utils.hpp, include/cute/algorithm/tuple_algorithms.hpp, include/cutlass/detail/layout.hpp, include/cutlass/epilogue/collective/sm90_epilogue_tma_warpspecialized.hpp, include/cutlass/gemm/collective/builders/sm90_gmma_builder.inl, include/cutlass/gemm/collective/sm90_mma_tma_gmma_rs_warpspecialized_mixed_input.hpp, include/cutlass/gemm/gemm.h
Improve mixed dtype kernel performance with offline weight reordering
=> Improve sm90 mixed dtype kernel

python/cutlass/backend/evt/frontend/python_ast.py, python/cutlass/epilogue/__init__.py, python/cutlass/epilogue/evt_ops.py, test/python/cutlass/evt/evt_compute_sm80_90.py
To discuss and solve #1807 
I think that more epilogue types should be supported...
=> EVT: add maximum/minimum evt support

include/cute/util/print.hpp
https://github.com/NVIDIA/cutlass/discussions/1867
=> Add a print for the uint{x}b_t type.

PUBLICATIONS.md
=> Update publication list

include/cute/container/array_subbyte.hpp
https://github.com/NVIDIA/cutlass/issues/1879
=> fix undefined in device code error

media/docs/cute/04_algorithms.md
=> Fix CuTe README Typo

include/cutlass/platform/platform.h
Small fixes found when trying to upgrade:
1. Add back in dropped header
=> Small tweaks found when upgrading to 3.6 from 3.5.1

include/cutlass/integer_subbyte.h
=> Fix assertion in integer_subbytes.h

.gitignore, CONTRIBUTORS.md, include/cutlass/gemm/collective/builders/sm90_gmma_builder.inl, include/cutlass/gemm/collective/collective_mma.hpp, include/cutlass/gemm/collective/sm90_mma_array_tma_gmma_ss_warpspecialized_fp8.hpp, include/cutlass/gemm/dispatch_policy.hpp, python/cutlass_library/library.py, python/cutlass_library/sm90_utils.py, tools/library/src/grouped_gemm_operation_3x.hpp
- New Mainloop Collective
- Builder support
- Profiler support
=> Hopper Grouped GEMM support for FP8 Accum

examples/67_hopper_fp8_warp_specialized_gemm_with_blockwise_scaling/67_hopper_fp8_warp_specialized_gemm_with_blockwise_scaling.cu, examples/67_hopper_fp8_warp_specialized_gemm_with_blockwise_scaling/67_hopper_fp8_warp_specialized_gemm_with_groupwise_scaling.cu, examples/68_hopper_fp8_warp_specialized_grouped_gemm_with_blockwise_scaling/68_hopper_fp8_warp_specialized_grouped_gemm_with_blockwise_scaling.cu, examples/68_hopper_fp8_warp_specialized_grouped_gemm_with_blockwise_scaling/CMakeLists.txt, examples/68_hopper_fp8_warp_specialized_grouped_gemm_with_blockwise_scaling/hopper_fp8_commandline.hpp, examples/68_hopper_fp8_warp_specialized_grouped_gemm_with_blockwise_scaling/reference/host/gemm_with_groupwise_scaling.h, examples/81_blackwell_gemm_blockwise/81_blackwell_gemm_blockwise.cu, examples/81_blackwell_gemm_blockwise/81_blackwell_gemm_groupwise.cu, examples/81_blackwell_gemm_blockwise/CMakeLists.txt, examples/CMakeLists.txt, include/cutlass/detail/sm100_blockwise_scale_layout.hpp, include/cutlass/gemm/collective/builders/sm100_blockwise_umma_builder.inl, include/cutlass/gemm/collective/builders/sm90_gmma_builder.inl, include/cutlass/gemm/collective/collective_builder.hpp, include/cutlass/gemm/collective/collective_mma.hpp, include/cutlass/gemm/collective/fp8_accumulation.hpp, include/cutlass/gemm/collective/sm100_mma_warpspecialized_blockwise_scaling.hpp, include/cutlass/gemm/collective/sm90_mma_array_tma_gmma_rs_warpspecialized_mixed_input.hpp, include/cutlass/gemm/collective/sm90_mma_array_tma_gmma_ss_warpspecialized_fp8.hpp, include/cutlass/gemm/collective/sm90_mma_array_tma_gmma_ss_warpspecialized_fp8_blockwise_scaling.hpp, include/cutlass/gemm/collective/sm90_mma_tma_gmma_ss_warpspecialized_fp8_blockwise_scaling.hpp, include/cutlass/gemm/dispatch_policy.hpp, include/cutlass/gemm/kernel/gemm_universal.hpp, include/cutlass/gemm/kernel/sm100_gemm_tma_warpspecialized_mma_transform.hpp, include/cutlass/gemm/kernel/sm90_gemm_array_tma_warpspecialized_cooperative.hpp, include/cutlass/gemm/kernel/sm90_gemm_array_tma_warpspecialized_pingpong.hpp
- Blockwise and Groupwise GEMM improvements for Hopper.
- Blockwise and Groupwise GEMM for Blackwell.
- Blockwise Grouped GEMM for Hopper.
- Static ScalePromotionInterval for Hopper FP8 GEMMs.
=> Blockwise and Groupwise GEMM for Blackwell and Improvements for Hopper

include/cutlass/gemm/kernel/sm90_gemm_array_tma_warpspecialized_cooperative.hpp, include/cutlass/gemm/kernel/sm90_gemm_array_tma_warpspecialized_pingpong.hpp, include/cutlass/gemm/kernel/sm90_gemm_tma_warpspecialized_pingpong.hpp, include/cutlass/gemm/kernel/tile_scheduler_params.h
=> Fix SM90 beta=1 hang and stream-K launch errors

include/cute/container/tuple.hpp, include/cute/layout.hpp, include/cute/numeric/arithmetic_tuple.hpp, include/cute/tensor_impl.hpp, include/cutlass/functional.h
When updating to the latest version, the cute program compiled with numerous warnings, so I helped fix it.
=> suppress compilation warnings

media/docs/cpp/blackwell_cluster_launch_control.md
=> Fix broken links and alt text in cluster launch control docs

PUBLICATIONS.md
Adds "Generalized Neighborhood Attention" to list of publications.
https://arxiv.org/abs/2504.16922
CC @hwu36 @thakkarV
=> [CUTLASS] Add GNA to PUBLICATIONS.md

examples/77_blackwell_fmha/77_blackwell_fmha.cu, examples/77_blackwell_fmha/CMakeLists.txt, examples/77_blackwell_fmha/collective/sm100_fmha_fwd_mainloop_tma_warpspecialized.hpp, examples/77_blackwell_fmha/kernel/sm100_fmha_fwd_kernel_tma_warpspecialized.hpp
=> v4.0 update.

examples/77_blackwell_fmha/77_blackwell_fmha.cu, examples/77_blackwell_fmha/77_blackwell_fmha_gen.cu, examples/77_blackwell_fmha/77_blackwell_mla.cu, examples/77_blackwell_fmha/CMakeLists.txt, examples/77_blackwell_fmha/collective/sm100_fmha_fwd_epilogue_tma_warpspecialized.hpp, examples/77_blackwell_fmha/collective/sm100_fmha_fwd_mainloop_tma_warpspecialized.hpp, examples/77_blackwell_fmha/collective/sm100_fmha_gen_mainloop_warpspecialized.hpp, examples/77_blackwell_fmha/collective/sm100_fmha_load_cpasync_warpspecialized.hpp, examples/77_blackwell_fmha/kernel/sm100_fmha_fwd_kernel_tma_warpspecialized.hpp, examples/77_blackwell_fmha/kernel/sm100_fmha_mla_tma_warpspecialized.hpp, examples/77_blackwell_fmha/reference/fmha_fwd_reference.hpp, examples/77_blackwell_fmha/reference/fmha_mla_reference.hpp, examples/77_blackwell_fmha/reference/reference_abs_error.hpp
=> v4.0 update v2.

include/cute/atom/mma_traits.hpp
The entry and descriptions were jumbled up.
=> Corrected minor nit in mma_traits.hpp

examples/05_batched_gemm/batched_gemm.cu
Hello! I made documentation updates in the <code>batch_gemm</code> example code as suggested in this issue: https://github.com/NVIDIA/cutlass/issues/1773.
=> Made documentation updates in batched_gemm.cu

media/docs/cpp/cute/02_layout_algebra.md
Addresses #2520, regarding confusing description of layout composition 
Adds:
- more exposition
- worked examples of compositions with multiple modes.
=> [DOC] Add more exposition to composition example

examples/01_cutlass_utilities/cutlass_utilities.cu
=> fix a typo.

examples/python/CuTeDSL/blackwell/fmha.py
=> fix gqa issue for blackwell fmha.py

include/cutlass/matrix.h
I asked chatgpt to find bugs in matrix.h, this is the result.
=> Fix bugs in matrix.h

media/docs/cpp/cute/03_tensor.md
=> Fix doc cute 03_tensor.md link typo
