examples/02_cutlass_utilities/cutlass_utilities.cu
CUDA 9 lacks host-side conversions from float=>half. Instead, we must reinterpret_cast<> from cutlass::half_t => half.
=> Fixed cutlass_utilities example. 

CMakeLists.txt, cutlass/coord.h, cutlass/cutlass.h, cutlass/gemm/gemm_mainloop.h, cutlass/gemm/igemm_multiply_add.h, cutlass/gemm/linear_scaling.h, cutlass/gemm/threadblock_swizzle.h, cutlass/reduction/batched_reduction.h, cutlass/reduction/threadblock_swizzle.h, cutlass/wmma_matrix.h, tools/test/unit/core/layout_verification.cu, tools/test/unit/core/layout_verification.h, tools/test/unit/core/tile_iterator.cu, tools/util/half.h, tools/util/reference/detail/inner_product.h, tools/util/reference/device/thread/gemm.h, tools/util/type_traits.h
Enable compilation with clang with these options:
```
$ cmake -DCUDA_COMPILER=clang -DCMAKE_CXX_COMPILER=/path/to/clang++ [other options]
```
Compilation for sm_75 requires a very recent clang build (r359248 or newer).
Some fp16 unit tests are currently failing, if cutlass is compiled with clang. I didn't find the root cause yet.
Performance will also need fair amount of tuning. Specifically clang requires huge increase to the default unroll thresholds in order to reach reasonable performance, but there's still substantial room for improvement.
=> Make CUTLASS compileable with Clang.

CMakeLists.txt
clang++ does not apply __CUDACC_VERSION_MAJOR__ and __CUDACC_VERSION_MINOR__ during compilation. These changes provide these explicitly from CMake.
=> Clang GPU compilation requires explicit CUDACC version flags

media/docs/quickstart.md
Need Python 3.6 for enum.auto() in `tools/library/scripts`.
=> Need Python 3.6 for enum.auto()

tools/library/CMakeLists.txt
#70 only updates the documentation. This commit reflects this bump in python version to the CMake configuration as well.
=> update tools/library/CMakeLists to require python 3.6 according to #70

CHANGELOG.md, README.md, examples/03_visualize_layout/CMakeLists.txt, examples/06_splitK_gemm/splitk_gemm.cu, examples/07_volta_tensorop_gemm/volta_tensorop_gemm.cu, examples/08_turing_tensorop_gemm/turing_tensorop_gemm.cu, examples/CMakeLists.txt, include/cutlass/arch/mma.h, include/cutlass/arch/mma_sm80.h, media/docs/quickstart.md, tools/util/include/cutlass/util/host_tensor_planar_complex.h
- Updated mma_sm80.h to avoid perf penalty due to reinterpret_cast<>.
- Enhancement to CUTLASS Utility Library's `HostTensorPlanarComplex` template to support copy-in and copy-out
- Added `test_examples` target to build and test all CUTLASS examples
=> Updated mma_sm80.h to avoid perf penalty due to reinterpret_cast<>.

include/cutlass/epilogue/threadblock/predicated_tile_iterator.h, include/cutlass/gemm/kernel/gemm.h, include/cutlass/gemm/kernel/gemm_array.h, include/cutlass/gemm/kernel/gemm_batched.h, include/cutlass/gemm/kernel/gemm_planar_complex.h, include/cutlass/gemm/kernel/gemm_planar_complex_array.h, include/cutlass/gemm/kernel/gemm_universal.h, include/cutlass/gemm/kernel/sparse_gemm.h
Minor edits to CUTLASS 2.3.0. 
- Fixes `__shfl_sync()` call for broadcasting warp index.
- Avoids generic memory in epilogue
=> CUTLASS 2.3.0

include/cutlass/gemm/thread/mma_sm60.h, test/unit/conv/device/CMakeLists.txt, test/unit/conv/device/conv2d_fprop_implicit_gemm_f16nhwc_f16nhwc_f16nhwc_simt_f16_sm50.cu, test/unit/conv/device/conv2d_fprop_implicit_gemm_f16nhwc_f16nhwc_f16nhwc_simt_f16_sm60.cu
This patch made fp16 related conv testable for arch SM50.
Signed-off-by: Peter Han <fujun.han@iluvatar.ai>
=> HFMA2 Convolutions for SM60 onwards 

include/cutlass/conv/device/implicit_gemm_convolution.h, include/cutlass/gemm/device/gemm.h, include/cutlass/gemm/device/gemm_array.h, include/cutlass/gemm/device/gemm_batched.h, include/cutlass/gemm/device/gemm_complex.h, include/cutlass/gemm/device/gemm_sparse.h, include/cutlass/gemm/device/gemm_universal_base.h, include/cutlass/reduction/device/reduce_split_k.h
This error will cause workspace initialize operation run on the default stream which might differ from the stream that gemm kernel runs on. It happens when explicitly pass a non-default stream to CUTLASS gemm kernel.
Signed-off-by: Peter Han <fujun.han@iluvatar.ai>
=> Bugfix: memsetAsync uses wrong default stream

include/cutlass/conv/device/implicit_gemm_convolution.h, tools/library/scripts/generator.py
- Add a sliced-K tile size kernel instance to the library for Turing 1688 TensorOp
- Fix num warps calculations in implicit gemm header to account for slice-K
=> Fix for issue #211

include/cutlass/reduction/device/tensor_reduce.h
With this patch, reduction/device level cases could all pass on environment of V100 w/ CUDA-10.0.
Below shows the reduction/device test cases status comparison w/o and w/ this patch.
Before:  
```
Note: Google Test filter = -SM75*:SM80*
[==========] Running 26 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 26 tests from Reduction_TensorReduce
[ RUN      ] Reduction_TensorReduce.nhwc_reduce_w_f32x8_f16x8
[       OK ] Reduction_TensorReduce.nhwc_reduce_w_f32x8_f16x8 (84738 ms)
[ RUN      ] Reduction_TensorReduce.nhwc_reduce_w_f32x2_f16x2
[       OK ] Reduction_TensorReduce.nhwc_reduce_w_f32x2_f16x2 (20963 ms)
[ RUN      ] Reduction_TensorReduce.nhwc_reduce_w_f32x1_f16x1
[       OK ] Reduction_TensorReduce.nhwc_reduce_w_f32x1_f16x1 (10443 ms)
[ RUN      ] …
```
=> Bugfix: typo, make reduction device cases passed

CHANGELOG.md, CONTRIBUTORS.md, README.md
Listed Matthew Nicely as the CUTLASS product manager.
Also clarified the deprecation announcement for older NVIDIA GPU platforms.
=> Listed Matthew Nicely as the CUTLASS product manager.

include/cutlass/epilogue/thread/activation.h, include/cutlass/epilogue/thread/linear_combination_gelu.h, include/cutlass/epilogue/thread/linear_combination_generic.h, include/cutlass/epilogue/thread/linear_combination_hardswish.h, include/cutlass/epilogue/thread/linear_combination_sigmoid.h, include/cutlass/epilogue/thread/linear_combination_silu.h
Since Sigmoid and GeLU epilogue functors are almost identical, I propose to refactor them. The motivation is to make it easy to add another functors.
Now Sigmoid and GeLU epilogue functors are defined as:
```
using LinearCombinationSigmoid = LinearCombinationGeneric<Sigmoid, ElementOutput_, Count, ElementAccumulator_,
ElementCompute_, FloatRoundStyle::round_to_nearest>;
using LinearCombinationGELU = LinearCombinationGeneric<GELU, ElementOutput_, Count, ElementAccumulator_,
ElementCompute_, FloatRoundStyle::round_to_nearest>;
```
I'm going to add two new functors for `SiLU` and `HardSwish` activation, which can be implemented in the same manner.
What do you think? @hwu36
=> Refactor GELU and Sigmoid epilogue to use a common template (and add SiLu, Hardswish epilogue)

include/cutlass/gemm/kernel/gemm_grouped.h
Added missing synchronization to avoid WAR hazards between tiles in Grouped GEMM. Compute Sanitizer `--tool=racecheck` reports zero errors now.
=> Added missing synchronization to avoid WAR hazards between tiles in Grouped GEMM

include/cutlass/epilogue/thread/activation.h, include/cutlass/fast_math.h
Currently, trying to use sigmoid activation with `half_t` results in a compile error:
```
error: no instance of overloaded function "cutlass::exp" matches the argument list                                                                                                                                  
argument types are: (cutlass::half_t)       
```
=> Support half precision sigmoid activation

include/cutlass/epilogue/thread/activation.h, include/cutlass/epilogue/thread/linear_combination_residual_block.h, test/unit/conv/device/conv2d_fprop_with_broadcast_sm75.cu, test/unit/conv/device/conv2d_with_broadcast_testbed.h
Following the discussion in https://github.com/NVIDIA/cutlass/discussions/347, this is my proposal for enabling full fusion of residual block in deep neural network, of the form `UnaryOp(BinaryOp(ActivationOp(TensorOp(X) + bias), residual))` where `residual` has the same shape as the output tensor. 
As discussed in https://github.com/NVIDIA/cutlass/discussions/347, `LinearCombinationBiasElementwise` epilouge already supports `elementwise((alpha x conv + beta x C) + per_channel_bias)`. What we need in deep learning, however, is `elementwise((conv + per_channel_bias) + C)`. Initially I extended `LinearCombinationBiasElementwise` with another template parameter to specify in which order to do two additions, but I decided to add a new implementation of an epilogue functor from scratch for the …
=> Add epilogue functor for residual block fusion

tools/library/scripts/library.py
Just found while reading this file.
=> Fix typo in scripts/library.py (wrong data size for u8)

include/cutlass/gemm/kernel/gemm.h
Otherwise we get gemm_k_iterations is uninitialized warnings.
=> Remove unused gemm_k_iterations in GemmKernel::Params

examples/05_batched_gemm/batched_gemm.cu, include/cutlass/gemm/device/gemm_array.h, media/docs/gemm_api.md
For my application, I want a batched GEMM with no fixed stride between matrices (in cuBLAS terms, `cublas*gemmBatched()` instead of `cublas*gemmStridedBatched()`). There's apparently a class that does exactly this (`cutlass::gemm::device::GemmArray`), however, it uses the wrong argument order for `GemmBatchedIdentityThreadblockSwizzle::get_tiled_block()` and therefore doesn't compile.
In this PR, I swap the order of the arguments and add a demo for `GemmArray` to show that it works, at least for the toy SGEMM in `examples/05_batched_gemm`.
I also tested it on my application (using FP16), and it appears to work perfectly. There might be more to it, but to me it looks like `GemmArray` is identical to `GemmBatched` in every way except actually fetching pointers to the element of the batch, …
=> Make cutlass::gemm::device::GemmArray usable

include/cutlass/arch/simd_sm61.h, include/cutlass/layout/tensor.h, media/docs/layout.md
* fix typo in media/docs/layout.md
* fix typo in include/cutlass/arch/simd_61.h
* fix stride comment errors in TensorLayout
=> Fix typo in docs, code comments

CHANGELOG.md, include/cutlass/arch/memory_sm80.h
- when cutlass is included in multiple compilation units
compiled with `-dc` OOB_NAN_F16x8 device constant is
instantiated multiple times causing
Multiple definition of '_ZN7cutlass4arch13OOB_NAN_F16x8E' error
This PR makes this variable a local constant as it is not
modified during runtime
Signed-off-by: Janusz Lisiecki <jlisiecki@nvidia.com>
=> Fix separate compilation `-dc`

include/cutlass/integer_subbyte.h
The type of max() of uint1b_t is assigned to uint4b_t, is that a bug?
=> numeric_limit for uint1b_t

tools/library/src/handle.cu
GemmUniversalOperation:: get_device_workspace_size() failed on SegmentFault without pointer of arguments provided.
=> [library] pass pointer of arguments to get_device_workspace_size() in gemm_universal()  

tools/util/include/cutlass/util/device_dump.h
Force unroll a loop that doesn't have compilation constant loop times is dangerous.
I cannot reproduce the failure using NVCC, but it did 100% crash using our clang tools while running examples/02_dump_reg_shmem.
Signed-off-by: Peter Han <fujun.han@iluvatar.ai>
=> [BUGFIX]: falsely unroll loop

tools/util/include/cutlass/util/debug.h
`CUDA_PERROR_EXIT ` can lead to incorrect usage (see e.g. [this description](https://www.cs.technion.ac.il/users/yechiel/c++-faq/macros-with-if.html)) because it contains an incomplete `if` expression. Consider:
```C++
if (condition)
CUDA_PERROR_EXIT(cudaFree(x))
else
free(x);
```
The author of the code forgot to add a semicolon after the macro. In that case, the `else` will bind to the `if` inside the macro definition, leading to code that the author did not intend or expect. It the author does use a semicolon, the code will not compile, which is awkward.
The change adds a `do while` around the `if`, which always requires a semicolon.
This PR also adds the text of the failing expression to the printed error message.
=> Fix CUDA_PERROR_EXIT and print failing expression

include/cutlass/epilogue/warp/tile_iterator_volta_tensor_op.h, include/cutlass/transform/thread/transpose.h
Compiler generates warning that such mismatch can produce problems with VS compilers ABI.
* I'm sorry, I closed previous PR by mistake (https://github.com/NVIDIA/cutlass/pull/451).
=> Fixed template struct/class declaration mismatch 

media/docs/implicit_gemm_convolution.md
Reading https://github.com/NVIDIA/cutlass/blob/master/media/docs/implicit_gemm_convolution.md#shared-memory-layouts, I was confused because the figure shows T11 and T16 accessing the same bank while the explanation says `{T8, T9, .., T16} do not access the same 128-bit bank`.
@hwu36 @manishucsd
=> Fix typo in shared memory layout description

include/cutlass/arch/memory.h
- adds missing commas
- adjusts misaligned usage of CUTLASS_DEVICE between
template declaration and specializations
Signed-off-by: Janusz Lisiecki <jlisiecki@nvidia.com>
=> Fix compilation in clang

include/cutlass/complex.h, include/cutlass/conv/kernel/implicit_gemm_convolution.h, include/cutlass/conv/kernel/implicit_gemm_convolution_fusion.h, include/cutlass/conv/kernel/implicit_gemm_convolution_strided_dgrad.h, include/cutlass/conv/kernel/implicit_gemm_convolution_with_fused_epilogue.h, include/cutlass/epilogue/threadblock/default_epilogue_tensor_op.h, include/cutlass/gemm/device/rank_2k.h, include/cutlass/gemm/device/symm.h, include/cutlass/gemm/kernel/default_gemm.h, include/cutlass/gemm/kernel/default_gemm_grouped.h, include/cutlass/gemm/kernel/gemv.h, include/cutlass/gemm/threadblock/default_mma.h, include/cutlass/platform/platform.h, include/cutlass/transform/thread/unaryOp.h
Hello.
There are two problems related to nvrtc in recent release:
I Using `std::is_same` instead of `platform::is_same`
II `#include <cuComplex.h>` was [removed](https://github.com/NVIDIA/cutlass/commit/12f4108ac2233022b92f0e3533c23bed399fcf45#diff-e61f0e1523fa79466124610cca6dbdb83da572fed0944c5e48af8814898d9059L27) from `cutlass/complex.h` includes for nvrtc.
I For me it is not clear what is the cutlass strategy about nvrtc.
1. Always use `platform::`.
2. Use cuda/std/some_std headers for nvrtc.
Looks ugly:
```
#if defined(__CUDACC_RTC__)
#include <cuda/std/cstdint>
#else
#include <cstdint>
#endif
```
Also [CUB](https://github.com/NVIDIA/cub) will be broken anyway, so one should use "safe headers" from something like [jitify](https://github.com/NVIDIA/jitify).
But safe headers from …
=> 2.9 fixes for nvrtc

include/cutlass/epilogue/threadblock/default_epilogue_tensor_op.h
I add a partial specialization on default_epilogue_tensor_op.h in https://github.com/SpringWave1/cutlass/blob/f7c491fcd8be2fc7d30f9de1f5c2ee146dcb40c3/include/cutlass/epilogue/threadblock/default_epilogue_tensor_op.h#L161-L183
The reason is that I want to fuse a dequant in my kernel and thus need an operation from s32 * scale = float. See details in QST issue.
https://github.com/NVIDIA/cutlass/issues/483
=> update on default_epilogue_tensor_op.h for specialization of float < int32_t * 4

include/cutlass/gemm/kernel/gemm_universal.h, tools/library/include/cutlass/library/library.h
Fix a few errors caused by trying to initialize a class member with itself. These errors can turn into errors if you compile with `-Winit-self`.
=> Fix init-self compiler warnings

examples/31_basic_syrk/basic_syrk.cu, examples/32_basic_trmm/basic_trmm.cu
This PR fixes a few typos in the SYRK and TRMM examples.
It appears that a different threadblock tile shape is used in each of these examples than is indicated by the comments (128x128x8).
The changes I've made here may render some additional comments regarding tile sizes in these files inaccurate or incomplete (e.g., "which offers good performance for large matrices" in line 40 and "(chosen by default)" in line 86 of examples/31_basic_syrk/basic_syrk.cu (similar cases occur in the TRMM example)). I'm happy to alter/remove any of these comments according to your advice.
=> Fix typos in SYRK and TRMM examples

examples/24_gemm_grouped/gemm_grouped.cu, include/cutlass/gemm/device/gemm_grouped.h, test/unit/gemm/device/testbed_grouped.h
This change enables grouped GEMM to correctly use the [`cudaOccupancyMaxActiveBlocksPerMultiprocessor `](https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__HIGHLEVEL.html#group__CUDART__HIGHLEVEL_1g5a5d67a3c907371559ba692195e8a38c) API, in part by setting  `cudaFuncAttributeMaxDynamicSharedMemorySize` when more than 48 KB of shared memory.
Example 24_gemm_grouped and unit test cutlass_test_unit_gemm_device_grouped each pass.
=> Fix occupancy calculation for grouped GEMM

include/cutlass/conv/kernel/implicit_gemm_convolution_strided_dgrad.h
This commit fixes a functional bug.  It let threadblock early exit if start_h >= H or start_w >= W since they are out of bound.  It only happens when stride_h > H or stride_w > W
@manishucsd @masahi
=> fix out of bound write bug in stride dgrad

include/cutlass/arch/mma.h, include/cutlass/arch/mma_sm50.h, include/cutlass/arch/mma_sm60.h, include/cutlass/arch/mma_sm61.h
As this is required by `cutlass::epilogue::warp::TileIteratorSimt` for instance
https://github.com/NVIDIA/cutlass/blob/5d0580807242429bfd2a2bf2e52ffc7434c6ee4e/include/cutlass/epilogue/warp/tile_iterator_simt.h#L93-L101
(`Operator` being an arch::Mma:
https://github.com/NVIDIA/cutlass/blob/5d0580807242429bfd2a2bf2e52ffc7434c6ee4e/include/cutlass/epilogue/warp/tile_iterator_simt.h#L68
)
=> Ensure all arch::Mma specializations have ElementC set

examples/06_splitK_gemm/splitk_gemm.cu
* fix type issue in example 06 explanations + some typos
* remove dead code
> there is this: `the number of elements per vector memory access (16)` and I am not sure if it's true. I thought it was something like `128/size of element` on recent device. I didn't touch that part
> there is an exception raised if the capacity is not starting by 7, it is raised for 8x devices even if the example runs on those devices (but may be not very performant because of tile sizes, etc.). May be the check should let 8x device run the example?
=> fix: fix types in example 06

include/cutlass/complex.h
Added `value_type` trait to complex to make it an easier drop-in replacement for std::complex.
=> Adding value_type to complex

examples/35_gemm_softmax/gemm_softmax.cu, examples/35_gemm_softmax/gemm_with_softmax.h
performance improvement by changing `ApplyShape` param.
This patch improves the performance of the element-wise operation followed after partial/full reduction operations of softmax.
Choosing different `ApplyShape` significantly influences the performance. A user is suggested to follow the suggestions in the comments of the code to choose `ApplyShape` parameter.
```
<1, 1024>:
m=1024, n=1024, k=512, batch = 16, GFLOPs: 54338.3  GFLOPs
<1, 128>:
m=1024, n=1024, k=512, batch = 16, GFLOPs: 78625  GFLOPs
<2, 64>:
m=1024, n=1024, k=512, batch = 16, GFLOPs: 75128.9  GFLOPs
```
CUDA 11.6, NVIDIA A100. frequence locked at 1005 MHz and power locked at 400W.
=> upstream applyshape optimization

include/cutlass/epilogue/thread/conversion_op.h
A member function set_k_partition is required for the instatiation of cutlass::gemm::kernel::Gemm, even if SplitKSerial is false
=> Add member function to Convert epilogue

include/cutlass/aligned_buffer.h, include/cutlass/conv/threadblock/conv2d_dgrad_output_gradient_tile_access_iterator_optimized.h, include/cutlass/epilogue/thread/conversion_op.h, include/cutlass/epilogue/threadblock/predicated_tile_iterator.h, test/unit/conv/device/conv2d_dgrad_implicit_gemm_f16nhwc_f16nhwc_f16nhwc_tensor_op_f16_sm80.cu
CUTLASS 2.10 bug fixes.
- bug fix in conv2d DGRAD implementation
- defined behavior in epilogue tile iterator; previous behavior was undefined
- rename `AlignedBuffer::Array` => `AlignedBuffer::ArrayType` to avoid shadowing template
=> CUTLASS 2.10 bug fixes

examples/23_ampere_gemm_operand_reduction_fusion/ampere_gemm_operand_reduction_fusion.cu
IMO example 23 has nothing to do with relu. This is only a reduction. This line might be copied from example 12.
=> fix: comment typo in example 23

include/cutlass/epilogue/thread/activation.h
After commit e773429f7e31db051a67daeb58ed35d20095de9b (PR #622, see [here](https://github.com/NVIDIA/cutlass/commit/e773429f7e31db051a67daeb58ed35d20095de9b#diff-751b5c4a895ed535eb3e6e1fb8196d23e31c554ceaaf75538c162915d165c67aR163)), the invocation of activation functions changes from `activation(intermediate)` to `activation(intermediate, params_)`, but `GELU_taylor` currently has no operator for this invocation.
@kerrmudgeon  @hwu36 @ANIKET-SHIVAM
=> [BugFix] Fix call of GELU_Taylor in LinearCombinationGeneric

examples/39_gemm_permute/gemm_permute.cu, include/cutlass/layout/permute.h
The last dimension of the new tensor should be N/(T2*T3), otherwise the size of it would be M * N * T2(should be M * N).
=> fix(permute.h): incorrect comment in `Tensor5DPermute20314`

include/cutlass/layout/permute.h
`col_permute_` and `row_permute_` can be uniquely determined by the input coordinate. They are private, and not being read by any other member functions. So they can be local variables.
See more at #644
=> refactor(permute): change unused class member to local var

examples/42_fused_multi_head_attention/CMakeLists.txt, examples/42_fused_multi_head_attention/attention_scaling_coefs_updater.h, examples/42_fused_multi_head_attention/debug_utils.h, examples/42_fused_multi_head_attention/epilogue_pipelined.h, examples/42_fused_multi_head_attention/epilogue_rescale_output.h, examples/42_fused_multi_head_attention/epilogue_thread_apply_logsumexp.h, examples/42_fused_multi_head_attention/find_default_mma.h, examples/42_fused_multi_head_attention/fused_multihead_attention.cu, examples/42_fused_multi_head_attention/gemm/custom_mma.h, examples/42_fused_multi_head_attention/gemm/custom_mma_base.h, examples/42_fused_multi_head_attention/gemm/custom_mma_multistage.h, examples/42_fused_multi_head_attention/gemm/custom_mma_pipelined.h, examples/42_fused_multi_head_attention/gemm_kernel_utils.h, examples/42_fused_multi_head_attention/iterators/epilogue_predicated_tile_iterator.h, examples/42_fused_multi_head_attention/iterators/make_residual_last.h, examples/42_fused_multi_head_attention/iterators/predicated_tile_access_iterator_residual_last.h, examples/42_fused_multi_head_attention/iterators/predicated_tile_iterator_residual_last.h, examples/42_fused_multi_head_attention/kernel_forward.h, examples/42_fused_multi_head_attention/mma_from_smem.h, examples/CMakeLists.txt, include/cutlass/platform/platform.h
Forward only for now.
Currently supports (and tested) on: A100 (f16/f32/bf16), V100 (f16/f32), P100 (f16/f32).
<details>
<summary>Main modifications and customizations to cutlass</summary>
We found ourselves extending cutlass's classes on several occasions:
(1) We subclassed the `threadblock::Mma` [classes](https://github.com/facebookresearch/xformers/tree/main/xformers/components/attention/csrc/cuda/mem_eff_attention/gemm) - mainly to support [doing the prologue early](https://github.com/facebookresearch/xformers/blob/fdbf3eb663c68ea95c965e6e2779e776b84e2db5/xformers/components/attention/csrc/cuda/mem_eff_attention/gemm/custom_mma_multistage.h#L256) (so when we start our second matmul, data is already loaded in memory and we don't have to wait for gmem)
(2) We took the classes from the …
=> ex42: Fused MHA imported from xFormers

include/cutlass/conv/conv2d_problem_size.h, include/cutlass/conv/conv3d_problem_size.h
Noticed a few typos on the equality overloaders in Conv2dProblemSize and Conv3dProblemSize.
The former compares height to the target width, and compares dilation_h twice instead of dilation_h and dilation_w.
The latter's just getting dilations wrong.
Haven't really seen it repeated elsewhere but will keep any eye out and commit if I find any.
=> Fix typos in conv problem sizes

include/cutlass/epilogue/threadblock/default_epilogue_simt.h
This PR adds two `#include` directives so that the definitions of `cutlass::gemm::warp::WarpSize` from "cutlass/gemm/warp/mma.h" and `cutlass::arch::OpClassSimt` from "cutlass/arch/mma.h" are visible to "cutlass/epilogue/threadblock/default_epilogue_simt.h". Without them, there are compiler errors when building the header standalone:
```
In file included from cutlass/include/cutlass/epilogue/threadblock/default_epilogue_simt.cu:1:
./cutlass/include/cutlass/epilogue/threadblock/default_epilogue_simt.h:351:32: error: no member named 'warp' in namespace 'cutlass::gemm'; did you mean simply 'warp'?
static int const kWarpSize = cutlass::gemm::warp::WarpSize<arch::OpClassSimt>::value;
^
./cutlass/include/cutlass/epilogue/warp/tile_iterator_simt.h:49:11: note: 'warp' declared here
namespace warp …
```
=> Add missing #include directives

include/cutlass/array.h
This PR adds `const`-correct overloads for `Array::{begin,end,rbegin,rend}`. These overloads are necessary for usage with [the GMock Container Matchers](http://google.github.io/googletest/reference/matchers.html#container-matchers), which cast the `Container` argument to a constant reference.
=> Add const overloads for iterator functions.

include/cutlass/arch/mma.h
This PR just adds a missing semicolon to arch/mma.h.
I figured it might not be worth either raising an issue or opening a PR, but the latter just seemed the most efficient.
=> Adds missing semicolon

include/cutlass/epilogue/threadblock/default_epilogue_tensor_op.h
This PR addresses #799 by re-enabling epilogues for alignments other than 4 when `int32_t` is used for accumulation.
=> Re-enable alignments for int32_t accumulators

include/cutlass/conv/kernel/default_conv2d_fprop_with_broadcast.h, include/cutlass/epilogue/thread/linear_combination_bias_elementwise.h, include/cutlass/epilogue/thread/linear_combination_bias_relu.h, include/cutlass/epilogue/thread/linear_combination_residual_block.h, include/cutlass/gemm/kernel/default_gemm_with_broadcast.h, test/unit/conv/device/conv2d_with_broadcast_testbed.h, test/unit/gemm/device/testbed_gemm_with_broadcast.h
When ElementC is INT8 and EpilogueOutputOp::ElementCompute is float, we should use float for compute
=> Fix type bug in conv2d/gemm with broadcast

examples/41_fused_multi_head_attention/kernel_forward.h, examples/45_dual_gemm/device/dual_gemm.h, examples/45_dual_gemm/dual_gemm.cu, examples/45_dual_gemm/dual_gemm_common.h, examples/45_dual_gemm/dual_gemm_run.h, examples/45_dual_gemm/kernel/dual_gemm.h, examples/45_dual_gemm/threadblock/dual_mma_base.h, examples/45_dual_gemm/threadblock/dual_mma_multistage.h
The two extensions are suggested for the `DualGemm` in the `examples/45_dual_gemm` folder:
1. Following the `GemmUniversalMode::kBatched` [implementation](https://github.com/NVIDIA/cutlass/blob/add4ba622f1cdebc145d1df0e9620c3c84c00a52/include/cutlass/gemm/kernel/gemm_universal.h#L481), batched mode is added to the `DualGemm`. `DualGemmMode::kBatched` and `SplitKSerial` are incompatible: `Status::kErrorInvalidProblem` is returned if both are set.
2. The `DualGemm` template currently assumes the same layout, `LayoutB`, for both right operand matrices `B0` and `B1`. This is problematic if the layouts of the two matrices are different. In particular, this may be the case when one of the matrices is row-major, while the other is a (column) vector that has to be broadcasted in column-major with …
=> Extend DualGemm: support batched mode + decouple B0/B1 layouts

include/cutlass/gemm/device/base_grouped.h
Otherwise I got `error: no matching function for call to 'min'` when building with clang.
=> min -> std::min

tools/library/scripts/generator.py
When channel_num=16, alignment=16 in fixed_channel/few_channel modes can win optimized mode, so I added alignment=16 as well
=> Add fixed_channel and few_channel mode to int8 in generator

include/cutlass/gemm/threadblock/threadblock_swizzle_streamk.h
Hello.
There are no "complex" c++ headers during nvrtc compilation. Looks like iostream, core_io and trace.h are used only for Debug Print().
So I hide them.
=> Hide streams and typinfo from nvrtc

include/cutlass/epilogue/thread/linear_combination_bias_elementwise.h, include/cutlass/epilogue/thread/linear_combination_bias_relu.h, include/cutlass/epilogue/thread/linear_combination_residual_block.h
As per the suggestion in this question https://github.com/NVIDIA/cutlass/issues/783#issuecomment-1408687889 I experimented with toggling storing the T matrix off for speed. This gave us 5-6% throughput speed up for our problem size int8-int8-fp16 matmul. Wonder if it would be worth upstreaming exposing this option?
=> expose StoreT parameter for potential speed

include/cutlass/gemm/device/base_grouped.h
`std::vector<T>::size_type` is unsigned type, so let's iterate over unsigned type as well
Discovered, while trying to enable PyTorch building without `-Wno-sign-compare` warning suppression, see https://github.com/pytorch/pytorch/actions/runs/4418987999/jobs/7746850762#step:10:10532
=> Fix sign-compare warning in `reorder_array`

include/cutlass/functional.h
Should fix https://github.com/pytorch/pytorch/pull/94188 and potentially https://github.com/NVIDIA/cutlass/issues/4.
I used `>=  700` as cutlass==3.0 drops Pascal support, but let me know if I should decrease the version in this check.
=> add guards for __CUDA_ARCH__ >= 530

include/cute/arch/copy_sm75.hpp, include/cute/arch/util.hpp, include/cutlass/arch/memory_sm75.h
This PR adds preprocessor checks to enable the shared memory intrinsics `__cvta_generic_to_shared` and `__nvvm_get_smem_pointer`, as well as the `ldmatrix` PTX instructions, on Clang. Preventing these intrinsics from being used is a significant latency regression on Clang.
=> Enable shared memory intrinsics and ldmatrix PTX on Clang.

include/cutlass/gemm/device/gemm_universal_adapter.h
The 3.x [`GemmUniversalAdapter::operator()(cudaStream_t)`](https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/device/gemm_universal_adapter.h#L388) method is `const`-qualified. This is problematic, as it calls a non-`const`-qualified method [`run(Params&, cudaStream_t)`](https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/device/gemm_universal_adapter.h#L327) from the same class.
Indeed, replacing `gemm.run()` call with `gemm()` [here](https://github.com/NVIDIA/cutlass/blob/master/examples/48_hopper_warp_specialized_gemm/48_hopper_warp_specialized_gemm.cu#L378) in the `48_hopper_warp_specialized_gemm.cu` example leads to a compilation error:
```
$ nvcc -gencode=arch=compute_90a,code=[sm_90a,compute_90a] -O0 -std=c++17 --expt-relaxed-constexpr …
```
=> Remove const qualifier from 3.x GemmUniversalAdapter::operator(cudaStream_t)

examples/41_fused_multi_head_attention/CMakeLists.txt, examples/41_fused_multi_head_attention/fmha_backward.cu, examples/41_fused_multi_head_attention/fmha_backward_test.py, examples/41_fused_multi_head_attention/fused_multi_head_attention_backward.cu, examples/41_fused_multi_head_attention/fused_multihead_attention_fixed_seqlen.cu, examples/41_fused_multi_head_attention/fused_multihead_attention_variable_seqlen.cu, examples/41_fused_multi_head_attention/gemm/custom_mma_pipelined.h, examples/41_fused_multi_head_attention/gemm/mma_from_smem.h, examples/41_fused_multi_head_attention/gemm_kernel_utils.h, examples/41_fused_multi_head_attention/iterators/predicated_tile_access_iterator_residual_last.h, examples/41_fused_multi_head_attention/kernel_backward.h, examples/41_fused_multi_head_attention/kernel_forward.h, examples/41_fused_multi_head_attention/piped_subprocess.py, tools/library/CMakeLists.txt
This adds the backward pass from xFormers.
I didn't get the courage to write the reference implementation in C++ (5 GEMMs + many inplace ops), so I wrote it in python/pytorch. Also makes debugging wrong values easier - it's easy to print/dump/compare intermediate values.
Data is passed from python<->C++ through stdin/stdout pipe, and tensors through temporary files.
```bash
make 41_fmha_backward
CUTLASS_BUILD_DIR=../../build python fmha_backward_test.py
```
cc @mnicely @hwu36
=> fMHA: Add backward pass

examples/41_fused_multi_head_attention/iterators/predicated_tile_access_iterator_residual_last.h
There is a dangling reference for the params_ class member that does not survive the iterator's constructor. This PR replaces the dangling reference with a copy.
=> Fix for dangling references in the MHA example

include/cute/arch/copy_sm90_desc.hpp
Types `CUtensorMapDataType` etc. are only defined when `cuda.h` is included, and when compiling CuTe with NVRTC it's not (as it's a host header):
```cpp
#if !defined(__CUDACC_RTC__)
#include <cuda.h>
#include <cinttypes>
#endif
...
```
New checks make sure undefined types are not use with NVRTC.
=> Add missing checks for NVRTC in CuTe

tools/library/scripts/generator.py
Seems like the optional `schedules` argument was forgotten in generation of the mixed-precision SM90 WGMMA 16-bit operators [here](https://github.com/NVIDIA/cutlass/blob/main/tools/library/scripts/generator.py#L4163) (whereas it is passed a few lines above [here](https://github.com/NVIDIA/cutlass/blob/main/tools/library/scripts/generator.py#L4136)). As a result, mixed-precision warp-specialized operator instances are not generated. This PR adds the missing argument to the `CreateGemmUniversal3xOperator` call.
=> Add missing schedules argument in SM90 WGMMA 16-bit op generation

include/cutlass/kernel_hardware_info.hpp
Currently in the `KernelHardwareInfo` class, `cudaGetDeviceProperties` is called [here](https://github.com/NVIDIA/cutlass/blob/main/include/cutlass/kernel_hardware_info.hpp#L60) just to get the number of SMs. `cudaGetDeviceProperties` is quite heavy and can take from ~1 to 10s of milliseconds to complete. As it is called under the hood of every `GemmUniversalAdapter::initialize` when using SM90 TMA warp-specialized cooperative and pingpong kernel schedules, this makes the use cases where the arguments must be re-initialized on every kernel invocation quite inefficient.
In this PR, the `cudaGetDeviceProperties` call is replaced with much more lightweight `cudaDeviceGetAttribute` to get the `cudaDevAttrMultiProcessorCount` only. This takes in the order of 10ns and is virtually invisible in …
=> Get SM count with cudaDeviceGetAttribute in KernelHardwareInfo

include/cutlass/epilogue/thread/linear_combination_clamp.h
Currently [`cutlass/epilogue/thread/linear_combination_clamp.h`](include/cutlass/epilogue/thread/linear_combination_clamp.h) cannot be compiled standalone. This PR addresses this issue; see the commit message.
=> Add missing #include directive.

include/cute/config.hpp
- clang 1.14 complains about missing function from a host call:
```
cutlass/include/cute/arch/util.hpp:106:32: error: no matching function for call to '__cvta_generic_to_shared' return static_cast<uint32_t>(__cvta_generic_to_shared(ptr));```
- fixes this by defining CUTE_HOST_DEVICE for clang as well
=> Fix cuTE compilation with clang

include/cutlass/numeric_conversion.h
Currently, `*Converter::operator()` requires a mutable object to invoke, and there are missing `static result_type convert(source_type const & source)` overloads for certain partial specializations of `*Converter` objects. This PR makes `operator()` const-correct and adds missing function overloads where appropriate.
=> Make operator() const-correct and add missing static functions.

include/cutlass/epilogue/thread/activation.h
We have observed a significant performance degradation when fusing a large fp16 GEMM (M=913920, N=1024, K=256) with GELU. 
For instance, on our device (A100-80GB), the plain GEMM runs in approximately 3.25ms using the optimal tile description. However, when fused with GELU, it increases to 12.14ms. (However, the performance gap is not consistently that large across different devices, we have found that on an sm_87 Orin GPU, the difference is relatively small. We suspect this may be due to differing bottlenecks).
We brokedown each of the operations in GELU, and discovered that the `division` and `erff` operations have the most significant impact on performance. The details are as follows:
| experiment                                     | time (ms) |
| …
=> replace division with multiplication in GELU

tools/library/scripts/generator.py
This pull request introduces the addition of 128x256 threadblock tiles to support 16b Hopper Warp Group Matrix Multiply-Accumulate (WGMMA) General Matrix Multiply (GEMM). This enhancement is motivated by performance evaluations that highlighted an opportunity for improvement on larger GEMM shapes.
We noticed that with the current tile configurations, we were not able to fully utilize the computational capabilities of the H100 PCIe with 114 Streaming Multiprocessors (SMs), particularly for larger GEMM shapes such as `7296x2048x12288`. Despite using the existing tile sizes, we were unable to achieve peak performance, indicating a gap that could be addressed by introducing larger threadblock tiles.
The graph attached to this PR showcases the performance comparison between the existing tiles …
=> Enhancement: Addition of 128x256 Threadblock Tiles for 16b Hopper Warp Group MMA GEMM

CUDA.cmake
Cmake won't detect CUDA libraries when they're installed to `/usr/lib/x86_64-linux-gnu`.
I previously thought it was just the environment I was on, but I'm noticing just now that most of the machines I use (all of which are on Ubuntu with an AMD chip) have CUDA libraries (among others) installed to that path.
This PR adds the path `lib/x86_64-linux-gnu` to CUDA paths in the cmake file.
=> Adds CUDA path for x86-64

include/cutlass/epilogue/collective/sm90_epilogue_tma_warpspecialized_bias_elementwise.hpp, include/cutlass/epilogue/thread/linear_combination_bias_elementwise.h, test/unit/gemm/device/sm90_gemm_f16_f16_f16_tensor_op_f32_cluster_warpspecialized_cooperative_bias_elementwise.cu, test/unit/gemm/device/sm90_gemm_f16_f16_f16_tensor_op_f32_cluster_warpspecialized_pingpong_bias_elementwise.cu
This MR adds a missing conversion from `ElementBias` to `ElementCompute` before calling `thread::LinearCombinationBiasElementwise` in the collective-level bias-elementwise epilogue.
cc @aakhundov
=> Add conversion from ElementBias to ElementCompute for collective bias-elementwise epilogue

python/setup.py
The setup.py does not set library dir for cuda, which might leads to link error:
```
ld: cannot find -lcudart: No such file or directory
```
=> Improve python api setup

test/unit/util/CMakeLists.txt, test/unit/util/rms_norm.cu, tools/util/include/cutlass/util/device_rmsnorm.h
Add [RMS normalization](https://arxiv.org/abs/1910.07467) kernel to `tools/utils/`, based on the existing layer norm kernel. This normalization method is used, in particular, by llama. It is essentially a simplified layer norm.
Two impls have been added - a naive one that works for any shape / dtype, and a relatively fast one for half + multiple of 8 size. Based on feedbacks I can simply copy more variants from the layer norm kernels.
@hwu36
=> Add RMS norm to device util

examples/41_fused_multi_head_attention/default_fmha_grouped.h, examples/41_fused_multi_head_attention/fmha_backward_test.py, examples/41_fused_multi_head_attention/fmha_grouped.h, examples/41_fused_multi_head_attention/fused_multi_head_attention_backward.cu, examples/41_fused_multi_head_attention/fused_multihead_attention_fixed_seqlen.cu, examples/41_fused_multi_head_attention/fused_multihead_attention_variable_seqlen.cu, examples/41_fused_multi_head_attention/gemm/custom_mma_multistage.h, examples/41_fused_multi_head_attention/gemm/custom_mma_pipelined.h, examples/41_fused_multi_head_attention/gemm/mma_from_smem.h, examples/41_fused_multi_head_attention/gemm_kernel_utils.h, examples/41_fused_multi_head_attention/iterators/default_warp_iterator_from_smem.h, examples/41_fused_multi_head_attention/iterators/predicated_tile_access_iterator_residual_last.h, examples/41_fused_multi_head_attention/iterators/transpose_warp_iterator.h, examples/41_fused_multi_head_attention/iterators/warp_iterator_from_smem.h, examples/41_fused_multi_head_attention/kernel_backward.h, examples/41_fused_multi_head_attention/kernel_forward.h, examples/41_fused_multi_head_attention/transform/tile_smem_loader.h
Upstream recent changes to fMHA that we did in xFormers.
Current version in CUTLASS: https://github.com/facebookresearch/xformers/commit/b6be33aecb5297f3f994568cf29e194a75e47667
Updating to: https://github.com/facebookresearch/xformers/commit/55a4798d99c350eca9d225a14003f226775e5f76
Full changelog: https://github.com/facebookresearch/xformers/commits/main/xformers/csrc/attention/cuda
**FW pass:**
* Change how we do the iterative softmax to reduce the number of operations + reduce calls to `__syncthreads()` (https://github.com/facebookresearch/xformers/commit/26884142271d5fbf897c69cc43dd0523e8f9f87a)
* Remove the "DISPATCH_BOOL" inside the kernel - this was inducing a lot of RF use for some reason. The idea was to check only once if we could skip all bounds checks (to avoid checking bounds …
=> Update fMHA kernels

PUBLICATIONS.md
This particular publication was pointing to another paper. Also, it points directly to a PDF while all other papers point to web pages.
=> Fix one publication

include/cute/util/print.hpp
Fixes issue #1040.
`cute::print` failed to compile when compiler flags `-Wformat   -Wformat-security   -Werror=format-security` were passed. 
With this commit, `cute::print` works also when it is passed a single string and does not emit warnings (even when these compiler flags are present).
=> Avoid cute::print compiler warnings with -Wformat-security

include/cutlass/gemm/kernel/sm90_tile_scheduler_stream_k.hpp
=> Make ouput_tile_index only visible on device

examples/48_hopper_warp_specialized_gemm/48_hopper_warp_specialized_gemm.cu
matrix B index swapped which fails the sanity check for non-square inputs.
quick fix addressing the issue https://github.com/NVIDIA/cutlass/issues/1088
=> fix matrix B indices

include/cute/arch/mma_sm90_desc.hpp
When compiling tensor.hpp related code, a warning will appear.
I fixed it. But I'm not sure if this is the expected format.
=> Fix GmmaDescriptor print format string error

include/cute/numeric/integer_subbyte.hpp, include/cutlass/integer_subbyte.h
The comparison operator `<=` for integer subbyte is incorrect. This fix addresses this issue.
=> [fix] fix comparison operator for integer_subbyte

include/cutlass/array.h
when I use `cutlass::epilogue::thread::LinearCombinationSigmoid`, I encounter the this error: `cutlass/include/cutlass/array.h(1549): error: no operator "-" matches these operands` 
Moving  operator "-" from line 1549 to 1548 can solve this error.
Discovered by @furong@pjlab.org.cn @suzhongling@pjlab.org.cn @xuhaoran@pjlab.org.cn
=> Change the position of minus sign in line1549 array.h

tools/util/include/cutlass/util/device_rmsnorm.h
Initially the variable `h4` is `half4`, but its last two fields are not used. Based on the semantics and the context, I believe it should be `half2`.
=> Fix type typo in rmsnorm

test/unit/util/rms_norm.cu, tools/util/include/cutlass/util/device_rmsnorm.h
The RMS kernel added in https://github.com/NVIDIA/cutlass/pull/979 uses a hard-coded epsilon value of 1e-6. I learned that recent popular language models such as llama 2 have been trained with eps = 1e-5, and using a slightly different eps can cause accuracy problems for such models on some inputs (see https://github.com/mlc-ai/mlc-llm/issues/923#issuecomment-1735066112).
This PR makes the eps parameter an optional argument, with the default value of 1e-5 to align with the layer norm kernel.
@hwu36
=> Allow changing epsilon parameter in RMS norm kernel

include/cutlass/complex.h
In 3.2.1 the `conj` implementation was changed from generic, templated one to listing trivial overloads for scalar types. There were no overloads for 64 bit integer types, so when the code was instantiated with such types the compiler found several close-matching overloads that would require conversion and report an error.
This PR adds the missing overloads.
=> Add missing int64 and uint64 overloads for conj

.github/ISSUE_TEMPLATE/config.yml
Adds an entry to the New Issue page with a link to the CUTLASS Discord.
Example from CCCL repo: https://github.com/NVIDIA/cccl/issues/new/choose
=> Add config.yml issue template with Discord link

include/cute/algorithm/axpby.hpp, include/cute/algorithm/tuple_algorithms.hpp
When I compile a test code in linux with g++9.4.0 and nvcc11.4, there are serval warnings:
I fixed it following the other code blocks.
=> fix missing return warning for repeat and axpby

media/docs/pipeline.md
Pipeline is now a folder instead of a singular header file.
EDIT: it appears that the link does not work when opened in the "Files changed" window. When I try it in the actual commit branch it does point to the correct place.
=> Fix broken pipeline link in docs

include/cute/algorithm/tuple_algorithms.hpp
1. While the `not` operator is functional in C++, its usage is rather restricted. Therefore, I recommend employing the more prevalent `!` symbol to denote logical negation, which would enhance comprehension for subsequent readers.
2. make the `else` code style following the other code blocks in this file.
Reference:
https://en.cppreference.com/w/cpp/language/operator_alternative
=> change 'not' to symbol '!' and unify the code style for 'else'

include/cute/container/tuple.hpp
=> Fix missing return warning for tuple_cat

CHANGELOG.md, README.md
This doc-only PR addresses the discussion at #1170 
1. `Mixed-Precision` to `Mixed-Input`. [`Mixed-Precision`](https://arxiv.org/abs/1710.03740) is taken by the GEMM data-type where inputs (DataType(`operandA`) == DataType(`operandB`) are mixed with a different accumulation data type (`F16*F16+F32` and `BF16*BF16+F32`). The code uses [cutlass::arch::OpMultiplyAddMixedInputUpcast](https://github.com/manishucsd/cutlass/blob/main/include/cutlass/arch/mma.h#L73) tag to navigate and communicate that input data types are mixed. It would be good to set a nomenclature that is consistent and distinguishes between `Mixed-Precision` and `Mixed-Input` use-case. 
2. Update the hyperlink for `Mixed Precision Ampere GEMMs` to the [PR#1084](https://github.com/NVIDIA/cutlass/pull/1084) which has detailed …
=> Doc only change to CUTLASS 3.3 changelog

include/cutlass/bfloat16.h
=> Fix `std::abs` overloading for `bfloat16_t`

include/cute/arch/copy_sm80.hpp
Enable L2::128B prefetch for cp.async, refer https://github.com/NVIDIA/cutlass/issues/1174
=> Enable L2::128B prefetch for cp.async by default

examples/41_fused_multi_head_attention/kernel_forward.h
=> Adding missing `typename`

include/cutlass/gemm/kernel/sm70_gemm.hpp
This works around a clang issue where blockIdx is of a different type.
=> Explicitly cast `blockIdx` to `uint3`

include/cutlass/epilogue/threadblock/epilogue_with_broadcast.h
Fixes an issue that existed since Stream-K support was added to epilogue with broadcast in #892 .
`reduce` [is supposed to offset destination iterator by the reduction fragment index](https://github.com/NVIDIA/cutlass/blob/main/include/cutlass/epilogue/threadblock/epilogue.h#L381-L382), not by 1 like the typical epilogue call. 
@jackkosaian @hwu36
=> Fix Stream-K reduce bug in epilogue with broadcast

include/cutlass/gemm/kernel/gemm_streamk_with_fused_epilogue.h
Followup to #1224.
A change in the stream-k threadblock swizzle ctor since 3.3 breaks single source GEMM with fused epilogue and stream-k. Multi-source was already corrected.
=> Fix bug in single source GEMM with residual + streamk

tools/util/include/cutlass/util/command_line.h
Fixes a different signedness compare warning:
```
../cutlass/tools/util/include/cutlass/util/command_line.h: In instantiation of ‘void cutlass::CommandLine::get_cmd_line_arguments(const char*, std::vector<value_t>&, char) const [with value_t = std::__cxx11::basic_string<char>]’:
../cutlass/tools/util/include/cutlass/util/command_line.h:222:29:   required from here
../cutlass/tools/util/include/cutlass/util/command_line.h:188:19: warning: comparison of integer expressions of different signedness: ‘int’ and ‘std::vector<std::__cxx11::basic_string<char> >::size_type’ {aka ‘long unsigned int’} [-Wsign-compare]
188 |       for (int i = 0; i < keys.size(); ++i) {
|                 ~~^~~~~~~~~~~~~~~
```
=> Use size_t index to iterate up to std::vector::size()

include/cutlass/transform/threadblock/predicated_tile_access_iterator_params.h
Currently, the default constructor of `PredicatedTileAccessIteratorParams` will invoke undefined behavior in its invocation of the `initialize` function. Specifically, it will attempt to read from the uninitialized variables `desc.element_size_bits` and `desc.advance_rank`. This PR changes the default constructors of both `*Params` and `*Desc` to zero-initialize all uninitialized members.
=> Remove undefined behavior from default constructor of PredicatedTileAccessIteratorParams.

include/cute/arch/cluster_sm90.hpp
Prevents `error: invalid % escape in inline assembly string` when compiling with clang.
=> Fix inline ptx escaping for predicates.

include/cutlass/epilogue/collective/epilogue_tensor_broadcast.hpp, test/unit/gemm/device/gemm_testbed_3x_tensor_broadcast.hpp, test/unit/gemm/device/sm90_gemm_f32_f32_f32_tensor_op_f32_tensor_broadcast.cu, tools/util/include/cutlass/util/reference/host/gett.hpp
EpilogueTensorBroadcast only supports per-row vector broadcast, because the bias stride is hardcoded.
It can easily support both if the bias stride is made conditional, and the original behavior is maintained by defaulting to per-row.
Existing unit tests with `EpilogueTensorBroadcast` pass, and equivalent tests with per-col bias have been added.
=> Allow per-column bias in EpilogueTensorBroadcast

examples/36_gather_scatter_fusion/gather_scatter_fusion.cu
The count of FMAs depends on the index-tensor-B rather than the entire tensor B. 
Additionally, there was an error in using 'n' instead of 'k' when determining the width of tensor B in the calculation of the stride.
=> Fix flops calculation and tensor b stride calculation in the example 36

include/cute/atom/mma_atom.hpp
fix the compilation warning for `tile_size_mnk`
=> fix tile_size_mnk compilation warning

include/cute/util/print.hpp
when I debug an int8 kernel, I found the print(int8_tensor) could not perfom as expected(show in the following picture). Although it's a feature support problem for nvcc. I think we can work around it first.
The following snippet can reproduce the problem with nvcc-11.4 and nvcc-12.1.
```cpp
#include <cute/tensor.hpp>
__global__ void foo() {
using namespace cute;
int8_t i8 = 1;
int16_t i16 = 1;
int32_t i32 = 1;
uint8_t u8 = 1;
uint16_t u16 = 1;
uint32_t u32 = 1;
short s = 1;
unsigned short us = 1;
print(i8); print("\n");
print(i16); print("\n");
print(i32); print("\n");
print(u8); print("\n");
print(u16); print("\n");
print(u32); print("\n");
print(s); print("\n");
print(us); print("\n");
}
int main() {
foo<<<1, 1>>>();
cudaDeviceSynchronize();
}
```
=> fix unrecognized print format specifier for int8/uint8

examples/08_turing_tensorop_gemm/turing_tensorop_gemm.cu
Modify some comments in code  examples/08_turing_tensorop_gemm/turing_tensorop_gemm.cu , because i found that there is some wrong description for A and B matrix‘s layout in line 143-144
=> Modify comments in code  examples/08_turing_tensorop_gemm/

include/cutlass/bfloat16.h
While working on this PR:https://github.com/pytorch/pytorch/pull/118935
I found that the current version of PyTorch's cutlass v3.3.0 does not build with the updates to flash_attention_v2. And that when updating the cutlass to v3.4.0 the following error occurred:
```Shell
meta/pytorch/aten/src/ATen/native/transformers/cuda/attention.cu -o caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/ATen/native/transformers/cuda/attention.cu.o
/home/drisspg/meta/pytorch/aten/src/ATen/../../../third_party/cutlass/include/cutlass/bfloat16.h(94): error: name followed by "::" must be a class or namespace name
static_assert(cutlass::platform::is_integral<T>::value && sizeof(T) == 4, "Requires 32-bit integer");
^
/home/drisspg/meta/pytorch/aten/src/ATen/../../../third_party/cutlass/include/cutlass/bfloat16.h(94): …
```
=> Add a missing platform include

include/cute/atom/copy_atom.hpp
The original `TiledShape_MN` was removed in a previous commit.
=> fix `tile_size(TiledCopy<Args...> const&)` error

include/cutlass/detail/layout.hpp, tools/util/include/cutlass/util/packed_stride.hpp
For group_gemm, specifying L is unnecessary; it can be set to Int<0> for a smaller stride size.
the data layout between cutlass2.x group_gemm lda and cutlass 3.x group_gemm stride can be identical, allowing users to utilize the same arguments when upgrading to the cutlass3.x API.
I have tested this with 57_hopper_grouped_gemm.
=> group gemm set stride L = cute::Int<0>

include/cute/stride.hpp
After updating to version 3.5, there are some compilation warnings for my code.
I help fix it.
=> fix stride compilation warning

python/cutlass/op/gemm.py
Currently the `tile_descriptions` method of a `cutlass.Gemm` has 2 errors when the `math_operation` of the `plan` is manually set:
```python
import torch
import cutlass
m = 128
n = m
k = m
dtype = torch.float32
plan = cutlass.Gemm(
element=dtype, layout=cutlass.LayoutType.RowMajor, element_accumulator=dtype
)
plan.opclass = cutlass.OpcodeClass.TensorOp
plan.math_operation = cutlass.MathOperation.multiply_add_fast_f32
for td in plan.tile_descriptions():
print(f"{td.procedural_name()} {td.math_instruction.math_operation}")
```
Running the above gives the following error
```
Traceback (most recent call last):
File "/notebooks/Cutlass/cutlass-fix/test_td.py", line 18, in <module>
print(plan.tile_descriptions())
File "/notebooks/Cutlass/cutlass-fix/build/__editable__.nvidia_cutlass-3.5.0.0-py3- …
```
=> Python `Gemm` `tile_descriptions` fix

include/cutlass/uint128.h, test/unit/core/CMakeLists.txt, test/unit/core/uint128.cu
When I use the addition operation with `cute::uint128`, the behavior is not as expected. The carry should not be determined solely by whether the sum is zero or not.
nvcc: release 11.4, V11.4.120 
host-compiler: g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
reproduce code and its output(z.hi should be 0x1):
```cpp
#include "cute/tensor.hpp"
__global__ void foo() {
using T = cute::uint128_t;
T x, y;
x = uint64_t(0xFFFFFFFFFFFFFFFF);
y = uint64_t(0x2);
T z = x + y;
printf("gpu\n");
printf("x.hi = 0x%llX lo = 0x%llX\n", x.hilo_.hi, x.hilo_.lo);
printf("y.hi = 0x%llX lo = 0x%llX\n", y.hilo_.hi, y.hilo_.lo);
printf("z.hi = 0x%llX lo = 0x%llX\n", z.hilo_.hi, z.hilo_.lo);
}
int main() {
using T = cute::uint128_t;
T x, y;
x = uint64_t(0xFFFFFFFFFFFFFFFF);
y = uint64_t(0x2);
T z = x + y; …
```
=> Fix uint128 operator add

include/cutlass/arch/memory.h, include/cutlass/numeric_types.h
tested by simple example
```cpp
#include <cutlass/numeric_types.h>
#include <cutlass/core_io.h>
#include <iostream>
int main() {
cutlass::half_t x = 2.25_hf;
std::cout << x << std::endl;
return 0;
}
/*
clang++ test.cc -I include -I/usr/local/cuda/targets/x86_64-linux/include
In file included from test.cc:4:
include/cutlass/numeric_types.h:55:11: error: unknown type name 'size_t'
55 | template <size_t... Seq>
|           ^
include/cutlass/numeric_types.h:58:11: error: unknown type name 'size_t'
58 | template <size_t N, size_t... Next>
|           ^
include/cutlass/numeric_types.h:58:21: error: unknown type name 'size_t'
58 | template <size_t N, size_t... Next>
|                     ^
include/cutlass/numeric_types.h:61:11: error: unknown type name 'size_t'
61 | template <size_t... Next>
| …
```
=> add missing header for size_t in `numeric_types.h`

media/docs/cute/02_layout_algebra.md
change line 348 to reflect correct layout.
`((2,4),(2,2)):((1,6),(2,12))` does not have cosize `24` changing it to `((2,2),(3,2)):((1,6),(2,12))`
=> Fixing Documentation Error in 02_layout_algebra.md

media/docs/cute/02_layout_algebra.md
This doc-only PR fixes the confusion between concatenated vs. composed layout in CuTe documentation in the examples for  ComposedLayout in layout_algebra.md. 
Issue #1497
=> [Documentation] Fixes the confusion between concatenated vs. composed layout in CuTe documentation 

test/unit/conv/device_3x/dgrad/sm90_conv1d_dgrad_implicit_gemm_f16_f16_f32_tensorop_f16.cu, test/unit/conv/device_3x/dgrad/sm90_conv2d_dgrad_implicit_gemm_f16_f16_f32_tensorop_f16.cu, test/unit/conv/device_3x/dgrad/sm90_conv3d_dgrad_implicit_gemm_f16_f16_f32_tensorop_f16.cu, test/unit/conv/device_3x/fprop/sm90_conv1d_fprop_implicit_gemm_f16_f16_f32_tensorop_f16.cu, test/unit/conv/device_3x/fprop/sm90_conv2d_fprop_implicit_gemm_f16_f16_f32_tensorop_f16.cu, test/unit/conv/device_3x/fprop/sm90_conv3d_fprop_implicit_gemm_f16_f16_f32_tensorop_f16.cu, test/unit/conv/device_3x/wgrad/sm90_conv1d_wgrad_implicit_gemm_f16_f16_f32_tensorop_f16.cu, test/unit/conv/device_3x/wgrad/sm90_conv2d_wgrad_implicit_gemm_f16_f16_f32_tensorop_f16.cu, test/unit/conv/device_3x/wgrad/sm90_conv3d_wgrad_implicit_gemm_f16_f16_f32_tensorop_f16.cu
All f16 tests use ElementAcc type in place of the ElementAct type. Looks like a copy-and-paste typo.
=> Fix typos in convolution tests

include/cute/atom/mma_atom.hpp
Some of the namings of the B-operand functions were directly copied from the A-operand counterpart, fixed the naming of the variables and comments to improve clarity.
=> Fix B operand variable name and comments

CMakeLists.txt, test/unit/CMakeLists.txt
(Re-push of #1384)
I am building the project in a restricted environment that does not allow network access (so FetchContent is not usable), and already have a pre-compiled build of GTest ready to go. With this change, I can pass `-DCUTLASS_USE_SYSTEM_GOOGLETEST=ON -DGTest_ROOT=/path/to/gtest-install` to CMake, and the tests will build using the specified install. A system install of GTest can also be picked up.
The second commit fixes a related issue: the test suite breaks when the `bin/` subdirectory is missing from the build tree, but it's the bundled-googletest logic that creates it. So we create that dir explicitly/unconditionally.
=>   Support use of external/system GTest installation

PUBLICATIONS.md
Adds "Faster Neighborhood Attention: Reducing the O(n^2) Cost of Self Attention at the Threadblock Level" to publications.
TLDR; Neighborhood attention requires treating the attention problem as two batched GETTs instead of GEMMs (row mode can be 2-D and 3-D instead of a single dimension as in NLP.)
=> Add Faster Neighborhood Attention to PUBLICATIONS

tools/util/include/cutlass/util/reference/device/thread/gemm.h
Traversing the length of array B_tile is incorrect.
=> Fix device thread `gemm.h` constructor

examples/cute/tutorial/sgemm_1.cu, examples/cute/tutorial/sgemm_2.cu, examples/cute/tutorial/sgemm_sm70.cu, examples/cute/tutorial/sgemm_sm80.cu, media/docs/cute/0x_gemm_tutorial.md
The static check against `CSmemLayout` in all of the CuTe sgemm examples checks against `size<0>` twice. 
This has only passed thus far because `size<0>(CSmemLayout{}) == size<1>(CSmemLayout{});`, but it isn't strictly correct (it would imply that `CSmemLayout` is an BLK_M x BLK_M matrix, rather than a BLK_M x BLK_N matrix).
=> Fix SMEM index for C in CuTe examples

include/cutlass/arch/barrier.h
I guess `mbarrier`s were never invalidated before. Fails ptxas.
See https://docs.nvidia.com/cuda/parallel-thread-execution/#parallel-synchronization-and-communication-instructions-mbarrier-inval
=> Fix mbarrier PTX typo

include/cutlass/gemm/kernel/sm90_gemm_array_tma_warpspecialized_cooperative.hpp
I have identified two potential out-of-bounds access issues in the 3.x version of the grouped gemm kernel: (specifically this line of code `problem_shape_MNKL = append<4>(params.problem_shape.get_problem_shape(work_tile_info.L_idx), Int<1>{});` )
1. Initialization of problem_shape_MNKL before entering the tile loop: If the total number of tiles is very low, some threadblocks may start with an invalid initial tile, leading to out-of-bounds access.
- This can be reproduced by `compute-sanitizer examples/57_hopper_grouped_gemm/57_hopper_grouped_gemm --m=1024 --n=1024 --k=640 --groups=3`
- The error message showed by compute-sanitizer is as followes. It says an invalid read at 12 bytes (which is th size of UnderlyingProblemShape) before the nearest allocation, indicating that it is caused by …
=> Fix potential out-of-bounds access in 3.x grouped gemm kernel

include/cutlass/functional.h
`hrsqrt` doesn't seem to be defined for SM 5.2
=> Build hotfix for SM 5.2 on 3.5.1

python/cutlass_library/generator.py
Adds 128x256 tile shapes to FP16/BF16 and FP8 generators. Also adds 1x1x1 clusters to all existing FP16/BF16/FP8 generators.
NOTE: it is important to set kernel filter (--kernels / CUTLASS_LIBRARY_KERNELS) to a non empty string and skip pruning to get all of the new configurations.
If profiling exhaustively, they can be set to `*`.
Number of CUTLASS 3.X GEMMs before this commit: 2868
Number of CUTLASS 3.X GEMMs after this commit: 4016
CC @thakkarV @IonThruster @depaulmillz
=> Stamp out 1x1x1 clusters, 128x256 CTA shape

include/cutlass/detail/helper_macros.hpp, include/cutlass/epilogue/collective/sm90_epilogue_tma_warpspecialized.hpp, include/cutlass/functional.h, test/unit/core/functional.cu
Correct namespace qualification of `isnan` in `cutlass/functional.h` so that functions in the header invoke `cutlass::isnan` for `cutlass::half_t`, instead of converting `cutlass::half_t` to `float` and invoking `std::isnan` (on host, or `::isnan` on device).
=> Fix isnan namespace qualification in cutlass/functional.h

python/cutlass_library/generator.py
- Generator builds with 64x256xK math instruction shapes for fp16, bf16, and fp8 GEMMs.
- Now instantiates 5476 CUTLASS 3.x GEMM kernels when only 4016 were instantiated before.
=> Instantiate More CUTLASS 3.x GEMM Kernels

include/cutlass/half.h
CC @thakkarV @Skylion007
Might be the easiest way to resolve PyTorch build failures like 
```
2024-08-12T22:44:12.1177715Z /var/lib/jenkins/workspace/aten/src/ATen/native/sparse/cuda/ComputeSparseTile.h(61): error: calling a __host__ function("std::numeric_limits< ::cutlass::half_t> ::infinity()") from a __device__ function("at::native::LargestValuesGreedy< ::at::native::IdentityOp> ::outOfBoundsFillValue< ::cutlass::half_t> ") is not allowed
2024-08-12T22:44:12.1179632Z 
2024-08-12T22:44:12.1181932Z /var/lib/jenkins/workspace/aten/src/ATen/native/sparse/cuda/ComputeSparseTile.h(61): error: identifier "std::numeric_limits< ::cutlass::half_t> ::infinity" is undefined in device code
2024-08-12T22:44:12.1183740Z 
2024-08-12T22:44:12.1185714Z …
```
=> add `CUTLASS_HOST_DEVICE` to `std::numeric_limits<cutlass::half_t>` functions

include/cutlass/matrix.h
=> Fix matrix.h: set_slice3x3 -> set_slice_3x3

include/cutlass/epilogue/fusion/sm90_visitor_compute_tma_warpspecialized.hpp
This is useful for e.g. function taking in 2 float inputs and turn them to complex
=> Support ComputeFn where output type differs from input type

include/cutlass/epilogue/collective/sm90_epilogue_tma_warpspecialized.hpp
=> Prefix a member template name with the template keyword.

include/cutlass/gemm/collective/sm90_mma_tma_gmma_ss_warpspecialized_fp8.hpp
For `BLOCK_SIZE_K=256`, `GmmaFP8Accumulation` has `accum_promotion_interval=4` but `mma_count_per_mainloop_iteration=8`, which makes a non-FP8-fast-accum kernel never promote to FP32 accumulators. This PR fixes the wrong assertion by changing `4` into the real number of MMA instructions issued.
=> Fix MMA promotion interval assertions

include/cute/atom/mma_atom.hpp
Cute provides a utility called `print_latex` for visualizing layouts, which can aid in designing layouts for GEMM problems. However, utilizing LaTeX is not straightforward due to several reasons:
1. LaTeX files must be compiled into PDF format before they can be utilized.
2. LaTeX tools are not commonly installed in many Linux environments, and the installation process can be resource-intensive, requiring significant disk space and numerous dependencies.
3. While online LaTeX platforms(like overleaf) can assist in setting up the environment, they come with limitations, such as restrictions on compilation time.
4. By default, LaTeX struggles to handle large graphs with numerous nodes efficiently, often resulting in errors such as "TeX capacity exceeded, sorry [main memory size=5000000]." …
=> Add print_svg for mma

test/unit/conv/cache_testbed_output.h
Fix typos in test/unit/conv/cache_testbed_output.h
=> Fix typos in test/unit/conv/cache_testbed_output.h

include/cutlass/epilogue/fusion/sm90_visitor_compute_tma_warpspecialized.hpp
According to the previous comment, `FooHomogeneous` should inherit from `Foo<A, A>`, which has the same effect as the type template param `B` has a default template argument `A`.
=> Fix typo in comment

include/cute/arch/mma_sm90.hpp, include/cute/arch/mma_sm90_gmma.hpp, include/cute/atom/mma_traits_sm90_gmma.hpp
This GMMA shape is being used in FA3 backward pass for headdim 256 (tile size 64 x 80, split into 2 WGs).
cc @thakkarV
=> Add GMMA shape m64n40k16

include/cutlass/gemm/kernel/gemm_universal_with_visitor.h
The phenomenon I encountered while using the epilogue visitor tree in C++ is quite strange...
In `examples/47_ampere_gemm_universal_streamk/ampere_gemm_universal_streamk_broadcast.cu`:
```cpp
using EVTKernelStreamK =
typename cutlass::gemm::kernel::DefaultGemmWithVisitor<
ElementA, LayoutA, cutlass::ComplexTransform::kNone, AlignmentA,
ElementB, LayoutB, cutlass::ComplexTransform::kNone, AlignmentB,
ElementC, LayoutC, AlignmentC,
ElementAccumulator,
ElementCompute,
cutlass::arch::OpClassTensorOp,
cutlass::arch::Sm80,
ThreadblockShape,
WarpShape,
InstructionShape,
EVTD,
cutlass::gemm::threadblock::ThreadblockSwizzleStreamK,
NumStages,
cutlass::arch::OpMultiplyAdd,
EVTEpilogueStages
>::GemmKernel;
using DeviceGemmStreamK = cutlass::gemm::device::GemmUniversalAdapter<EVTKernelStreamK>;
```
I …
=> Fix EVT for cutlass::gemm::kernel::DefaultGemmWithVisitor's behavior when constructing GemmUniversalAdapter

include/cutlass/epilogue/threadblock/default_thread_map_simt.h, include/cutlass/epilogue/threadblock/default_thread_map_tensor_op.h, include/cutlass/epilogue/threadblock/default_thread_map_volta_tensor_op.h, include/cutlass/epilogue/threadblock/default_thread_map_wmma_tensor_op.h, include/cutlass/transform/threadblock/regular_tile_iterator_pitch_linear.h, include/cutlass/transform/threadblock/regular_tile_iterator_pitch_linear_2dthreadtile.h
Without this fixes the build of Conv2d is problematic in NVRTC.
=> Include of regular_tile_iterator.h fixed for NVRTC

include/cutlass/gemm/collective/sm90_mma_tma_gmma_rs_warpspecialized_mixed_input.hpp
Since the [offline layout swizzling](https://github.com/NVIDIA/cutlass/pull/1883) has been merged, the dequantized weights can be loaded to a whole register now. Therefore, it's optimal to just pack the weights into one register when converting.
=> remove redundant hardcoded packing configs in mixed dtype gemm

include/cute/arch/mma_sm80.hpp, include/cute/atom/mma_traits_sm80.hpp, include/cute/container/array_subbyte.hpp
https://github.com/NVIDIA/cutlass/discussions/1846#discussioncomment-10879540
I find A/BLayout is wrong in ```struct MMA_Traits<SM80_16x8x256_S32U1U1S32_TN_XORPOPC>```.  so I correct it and append more MMA_Traits  support for binary gemm, such as **m8n8k128**, **m16n8k128** and **AND_POPC version binary mma op**
=> fix wrong A/BLayout in MMA_Traits for binary mma and append other MMA_Traits support 

include/cutlass/gemm/warp/mma_tensor_op_tile_iterator.h
support Layout::kFactor with 8
loading data from shared memory:
|0 | 16 | 32 | 48 | 64 | 80 | 96 | 112|
|-- | -- | -- | -- | -- | -- | -- | --|
|T0 | T1 | T2 | T3 | T4 | T5 | T6 | T7|
|T9 | T8 | T11 | T10 | T13 | T12 | T15 | T14|
|T18 | T19 | T16 | T17 | T22 | T23 | T20 | T21|
|T27 | T26 | T25 | T24 | T31 | T30 | T29 | T28|
=> feat: support kFactor 8 used in mma tensor op tile iterator

tools/util/include/cutlass/util/device_nhwc_pooling.h
Currently in nhwc_pooling, it is code on assumption of stride == kernel_size:
```
assert(filter_tensor_size.h() == stride.row() &&
filter_tensor_size.w() == stride.column());
```
In this PR,  I remove such restriction so that nhwc_pooling could work on general cases.
=> remove restriction of stride == kernel in nhwc_pooling

python/cutlass/backend/operation.py, python/cutlass_library/generator.py, python/cutlass_library/sm90_utils.py
Previously we had this error upon import:
```
File "/storage/home/cutlass/python/cutlass/backend/operation.py", line 39, in <listcomp>
_version_splits = [int(x) for x in __version__.split("rc")[0].split(".")]
^^^^^^
ValueError: invalid literal for int() with base 10: 'post1'
```
=> Fix `cutlass` python library with cuda `12.6.2.post1`

include/cutlass/arch/mma_sm60.h
a slip of the hand caused a calculation error
=> fix bug: arch/mma_sm60.h Mma<2,2,1> calculate wrong

python/cutlass/library_defaults.py
fix typo which will cause error when cuda version is 12.6.2.post1
=> Fix typo in library_defaults.py

include/cute/atom/mma_atom.hpp
Print SVG footer deserves a line break because print LaTeX has one.
=> Add Line Break for Print SVG

examples/67_hopper_fp8_warp_specialized_gemm_with_blockwise_scaling/67_hopper_fp8_warp_specialized_gemm_with_groupwise_scaling.cu, examples/67_hopper_fp8_warp_specialized_gemm_with_blockwise_scaling/CMakeLists.txt, examples/67_hopper_fp8_warp_specialized_gemm_with_blockwise_scaling/reference/host/gemm_with_groupwise_scaling.h, include/cutlass/gemm/collective/builders/sm90_gmma_builder.inl, include/cutlass/gemm/collective/fp8_accumulation.hpp, include/cutlass/gemm/collective/sm90_mma_tma_gmma_ss_warpspecialized_fp8_blockwise_scaling.hpp, include/cutlass/gemm/dispatch_policy.hpp
As we adopt narrower datatypes, traditional scaling methods struggle to maintain accuracy, particularly with 8-bit floating-point types (e.g., `e5m2_t`, `e4m3_t`). The typical GEMM operation uses tensorwise scaling with $D = alpha * (A @ B) + beta * C$, but narrower datatypes necessitate more finer-grained scaling techniques. Before we dive deep into groupwise scaling below is a glossary of various scaling methods:
1. **Tensorwise Scaling**: Uses a single scaling factor per tensor, applied in the epilogue.
2. **Rowwise Scaling**: Uses a row vector for scaling, with dimensions Mx1 for operand A and 1xN for operand B, avoiding the scaling along the reduction dimension. This can also be handled in the epilogue with EpilogueVisitorTree.
3. **Blockwise Scaling** …
=> Groupwise scaling along M for FP8 gemm

examples/61_hopper_gemm_with_topk_and_softmax/61_hopper_gemm_with_topk_and_softmax.cu, include/cutlass/epilogue/fusion/sm90_visitor_topk_softmax.hpp
Fixes a bug in generic top-k softmax EVT implementation that resulted in wrong results when k != 2 and k != 4.
This allows removal of the static assert requiring k to be either 2 or 4. Comment in example 61 is also fixed to reflect that any k value is now supported.
=> bugfix generic-k code in top-k with softmax

include/cutlass/epilogue/fusion/sm90_visitor_load_tma_warpspecialized.hpp
To enable FP8 grouped gemm with rowwise scaling in the epilogue, we need to be able to provide a list of pointers to the scales for each group. This PR extends Sm90Row/ColBroadcast to support PTRArray to handle this case. Now if the ElementInput type is specified as a pointer, the corresponding input is an array of pointers, enabling grouped gemm. For example in our case we define EVT nodes like this:
```
using XScale = cutlass::epilogue::fusion::Sm90ColBroadcast<
0,
TileShape,
ElementComputeEpilogue*, // Indicate input is array of pointers.
ElementComputeEpilogue,
cute::Stride<cute::Int<1>, cute::Int<0>, cute::Int<0>>>;
using WScale = cutlass::epilogue::fusion::Sm90RowBroadcast<
0,
TileShape,
ElementComputeEpilogue*, // Indicate input is array of pointers.
ElementComputeEpilogue, …
```
=> [EVT] Add support for Row/Col broadcast PtrArray

PUBLICATIONS.md
ParetoQ leverages CUTLASS mixed-precision W2A16 kernel. Special thanks to @hwu36 and @IwakuraRein for the support!
=> Add ParetoQ to PUBLICATIONS.md

include/cutlass/cuda_host_adapter.hpp
`cudaGetDriverEntryPointByVersion` has been added to drivers in 12.5, but we don't know at compile time the driver version. In particular, we can build with nvcc 12.8 for a 12.2 driver for instance, and this was causing the following error:
```
undefined symbol: cudaGetDriverEntryPointByVersion,
```
Closes https://github.com/NVIDIA/cutlass/issues/2079
NOTE: I was not able to test it with CUDA driver 12.5+
=> Always use cudaGetDriverEntryPoint with CUDA 12

include/cutlass/epilogue/fusion/sm90_visitor_load_tma_warpspecialized.hpp
#2033 added the ability for row/col broadcast nodes to accept ptr array arguments, however, during some followup refactoring it was broken. Specifically, there is an invalid type comparison that was added. This small PR fixes the issue by using a constexpr if to avoid the comparison if ptrarray is being used.
=> [EVT] Fix Row/Col broadcast with array arguments

examples/67_hopper_fp8_warp_specialized_gemm_with_blockwise_scaling/67_hopper_fp8_warp_specialized_gemm_with_blockwise_scaling.cu, examples/67_hopper_fp8_warp_specialized_gemm_with_blockwise_scaling/67_hopper_fp8_warp_specialized_gemm_with_groupwise_scaling.cu, examples/67_hopper_fp8_warp_specialized_gemm_with_blockwise_scaling/reference/host/gemm_with_groupwise_scaling.h, include/cutlass/gemm/collective/sm90_mma_tma_gmma_ss_warpspecialized_fp8_blockwise_scaling.hpp
Various improvements to "Groupwise scaling along M" (https://github.com/NVIDIA/cutlass/pull/2037) namely to address: https://github.com/NVIDIA/cutlass/issues/2087, context https://github.com/vllm-project/vllm/pull/11868#issuecomment-2646831621 
Improvements:
1) Multiple threads now participating in copy A scales
2) Predication when copying A scale loads, this means if there is partial M tile (due to the problem shape not being evenly divided by the M tile shape)
3) More commonly used scale layouts, currently CUTLASS uses a layout like:
```
(M_TILES, ScaleMsPerTile, K_TILES, L), ordered: (2, 0, 1, 3)
```
this PR moves to a layout of (i.e. standard M-major):
```
(M / ScaleGranularityM, K_TILES, L), ordered: (1, 0, 2)
```
making it much easier to integrate into inference libraries 
These …
=> Improvements for: Groupwise scaling along M for FP8 gemm

media/docs/quickstart.md
As the title implies, I added the Blackwell architecture to the list of supported architectures. Since it was already mentioned at the beginning, I simply included it in the list.
=> Add Blackwell to the list of architectures in quickstart.md

include/cute/layout.hpp
During compilation of a complex left-inverse kernel, NVCC 11.4 failed to build the implementation. I resolved the compiler-specific issues to improve the code robustness, then verified the fixes with NVCC 12.1.
=> fix-left-inverse-for-nvcc114

include/cutlass/gemm/kernel/sm90_gemm_tma_warpspecialized_cooperative.hpp, include/cutlass/gemm/kernel/sm90_gemm_tma_warpspecialized_pingpong.hpp
With the usual register allocation (producer 40, consumer 232) compiling Gemm with tile shape 256 x 208 (cooperative) or 128 x 208 (pingpong) show lots of register spilling (e.g. ~3000 bytes spill). For this case we can change the register allocation to producer 24, consumer 240, which avoids spills.
Cc @thakkarV @hwu36
=> [SM90] Change register allocation for TileN=208 to avoid spills

include/cutlass/epilogue/collective/builders/sm90_builder.inl
If TileN is not divisible by 32 (e.g, 208), by default EpiTile would be set to 128 x 32, which does not compile as TileN is required to be divisible by EpiTileN. We instead set EpiTileN to be gcd(32, TileN).
Cc @thakkarV @hwu36
=> Set EpiTile correctly when TileN is not divisible by 32

include/cute/config.hpp
I encountered a compile error when compiling cutlass@3.8.0. It seems to be a missing header <cstdint>. See also #2148.
```plain_text
...
[ 52%] Generating nvrtc/cute/atom/mma_traits_sm90.hpp
cd /tmp/mizuno-ai/spack-stage/spack-stage-cutlass-3.8.0-taomxjkncofl27l4ed6y4azkxfgb2yll/spack-build-taomxjk/test/unit/nvrtc && /mnt/sda/2022-0526/public/wuk/v0.23.0.12.3.0.12.20241120/spack/opt/spack/linux-debian11-zen2/gcc-13.2.0/cmake-3.30.5-a4w5ckchyi3ih7t4slujnfrhr4vsc64s/bin/cmake -DFILE_IN="/tmp/mizuno-ai/spack-stage/spack-stage-cutlass-3.8.0-taomxjkncofl27l4ed6y4azkxfgb2yll/spack-src/include/cute/atom/mma_traits_sm90.hpp" -DFILE_OUT="/tmp/mizuno-ai/spack-stage/spack-stage-cutlass-3.8.0-taomxjkncofl27l4ed6y4azkxfgb2yll/spack-build-taomxjk/test/unit/nvrtc/nvrtc/cute/atom/mma_traits_sm90.hpp" …
```
=> fix_missing_stdint

python/cutlass/backend/evt/passes/graph_drawer.py
Towards https://github.com/NVIDIA/cutlass/issues/2243
This PR lazily imports pydot, note that the annotations import is to only import for type annotations during type checking, not on import. 
cc @Henrylhtsang, @eellison, @thakkarV
=> Import pydot lazily

python/cutlass/backend/evt/frontend/frontend_base.py, python/cutlass/backend/evt/frontend/python_ast.py, python/cutlass/backend/evt/ir/dag_ir.py, python/cutlass/backend/evt/passes/pass_dag_2_tree.py, python/cutlass/epilogue/epilogue.py
Towards https://github.com/NVIDIA/cutlass/issues/2243
This PR makes cc a positional argument in the EVT classes. This removes the need to import the python cuda bindings to get the cc if cc is provided as a kwarg to `trace`.
=> Make cc a positional argument for most EVT infra

python/cutlass/__init__.py, python/cutlass/backend/arguments.py, python/cutlass/backend/compiler.py, python/cutlass/backend/conv2d_operation.py, python/cutlass/backend/evt/epilogue.py, python/cutlass/backend/frontend.py, python/cutlass/backend/gemm_operation.py, python/cutlass/backend/memory_manager.py, python/cutlass/backend/operation.py, python/cutlass/backend/reduction_operation.py, python/cutlass/backend/utils/device.py, python/cutlass/library_defaults.py, python/cutlass/op/conv.py, python/cutlass/op/gemm.py, python/cutlass/op/gemm_grouped.py, python/cutlass/utils/lazy_import.py, python/cutlass/utils/profiler.py
Towards https://github.com/NVIDIA/cutlass/issues/2243
This PR adds a util to import the above cuda.* modules lazily.
Other changes:
* import annotation to remove imports for type annotations unless type checking is running
* removing cuda.* types from default args to not eagerly import
=> Import cuda, cudart, nvrtc lazily

python/CuTeDSL/requirements.txt
Needs == for pip to parse the file
=> Fix typo in requirements.txt

examples/77_blackwell_fmha/collective/fmha_fusion.hpp
Current code cannot handle when trip count is smaller than `ceil_div(get<0>(tile_shape), get<1>(tile_shape))`.
=> Handle get_masked_trip_count for small length in fmha example

examples/77_blackwell_fmha/77_blackwell_mla_fwd.cu, examples/77_blackwell_fmha/CMakeLists.txt, examples/77_blackwell_fmha/collective/fmha_fusion.hpp, examples/77_blackwell_fmha/collective/sm100_fmha_fwd_epilogue_tma_warpspecialized.hpp, examples/77_blackwell_fmha/collective/sm100_fmha_mla_fwd_mainloop_tma_warpspecialized.hpp, examples/77_blackwell_fmha/collective/sm100_fmha_mla_load_tma_warpspecialized.hpp, examples/77_blackwell_fmha/common/pipeline_mla.hpp, examples/77_blackwell_fmha/kernel/fmha_causal_tile_scheduler.hpp, examples/77_blackwell_fmha/kernel/sm100_fmha_bwd_kernel_tma_warpspecialized.hpp, examples/77_blackwell_fmha/kernel/sm100_fmha_fwd_kernel_tma_warpspecialized.hpp, examples/77_blackwell_fmha/reference/fmha_fwd_reference.hpp
Add the prefill phase MLA with shape $d_{qk}=192 , d_{vo}=128$ for the Blackwell architecture in example 77. It supports both FP16 and FP8.
Mainly based on the implementation of fmha. The main changes are as follows:
+ Add PipelineTmaAsyncMla to support producer to acquire specific bytes of data.  since tileK is not equal to tileV when using MLA.
+ Optimize shared memory usage. 
+ Optimize register usage to reduce register spilling.
+ Add TileScheduler to optimize the causal mask case.
+ Add a second kind of causal mask implementation (with Q at the end of the matrix) to handle N_Q ≠ N_K, which is more commonly used.
Example 77 has new bins named `77_blackwell_mla_fwd_fp16` and `77_blackwell_mla_fwd_fp8`.
=> Add Blackwell MLA forward (shape: d=192, dv=128) implementation

examples/cute/tutorial/sgemm_sm80.cu
Hey I was running `sgemm_sm80.cu` example and printing out the tensor layouts, the code triggered a segfault when I added more printing logs, and `compute-sanitizer` shows it was due to `ldsm`.
I found that:
```
tCrA : ptr[16b](0x7f54b9fff9e0) o ((_2,_2),_4,(_2,_2,_2)):((_1,_2),_4,(_16,_32,_64))
tXrA : ptr[16b](0x7f54b9fff9e0) o (((_4,_2),_1),_4,_4):(((_1,_16),_0),_4,_32)
tCrB : ptr[16b](0x7f54b9fffae0) o (_2,_8,(_2,_2,_2)):(_1,_2,(_16,_32,_64))
tXrB : ptr[16b](0x7f54b9fffae0) o (((_4,_2),_1),_4,_4):(((_1,_16),_0),_4,_32)
```
where the copy pipeline stage (4) number doesn't match MMA's (8)
https://github.com/NVIDIA/cutlass/blob/8206e7a0f57a9a057cdd2c3bb4899bd5154a82e1/examples/cute/tutorial/sgemm_sm80.cu#L233-L234
https://github.com/NVIDIA/cutlass/blob/8206e7a0f57a9a057cdd2c3bb4899bd5154a8 …
=> Fix sgemm_sm80 example bug

include/cutlass/epilogue/thread/conversion_op.h
Add the interface types and functions to template class `epilogue::thread::Convert` which is required by `DefaultEpilogue`.
Testing code:
```c++
using CollectiveEpilogue = cutlass::epilogue::collective::DefaultEpilogue<
ElementD,
cutlass::detail::TagToStrideC_t<LayoutC>,
cutlass::detail::TagToStrideC_t<LayoutD>,
cutlass::epilogue::thread::Convert<ElementD, AlignmentD, ElementAccumulator>,
cutlass::gemm::EpilogueDefault>;
```
=> Fix epilogue::thread::Convert cannot be used with DefaultEpilogue

CMakeLists.txt
We need to guard the `$<BUILD_INTERFACE:${CUDA_TOOLKIT_ROOT_DIR}/include/cccl>` addition otherwise when downstream projects try to import cutlass targets they will run into errors ( https://github.com/rapidsai/raft/pull/2774 )
=> Support both CUDA 12 and 13 cccl header locations

python/pycute/swizzle.py
`self.` is missing in the implementation of Swizzle.
=> Make swizzle in pycute work

include/cutlass/gemm/kernel/sm100_gemm_array_tma_warpspecialized.hpp, include/cutlass/gemm/kernel/sm100_gemm_tma_warpspecialized.hpp, include/cutlass/gemm/kernel/sm100_gemm_tma_warpspecialized_mma_transform.hpp, include/cutlass/platform/platform.h
`constexpr` was incorrectly added to the function definition only for this architecture, breaking the compilation of Cutlass on Windows.
=> Fix sm100 gemm wrong static constexpr that breaks compilation on Windows

python/cutlass_library/heuristics.py, python/cutlass_library/heuristics_provider.py
There are some broken imports when installing `cutlass_library` using `setup_library.py`. This PR mirrors import logic from other files to fix this
=> Fix broken imports in heuristics_provider.py

examples/cute/tutorial/sgemm_sm80.cu
Original code failed with compilation error when the generic `gemm_nt`, `gemm_tn` are compiled. (by default, only the `half_t` specialization is built).
=> Fix Copy_Atom type mismatch in sgemm_sm80.cu

include/cute/atom/mma_atom.hpp
Correct the dimension descriptions in comments for tensor transformations:
- Line 265: Fix comment from (M,K) to (M,N) for C tensor transformation
- Line 343: Fix comment from (M,K) to (N,K) for B tensor transformation
These changes align the comments with the actual tensor dimensions being processed in the respective functions.
=> Fix dimension comments in TiledMMA thrfrg functions

include/cute/atom/copy_atom.hpp
During usage, I noticed that the output shape of `partition_S` does not match the documentation comments. Based on my understanding, the by-mode coalesce here https://github.com/NVIDIA/cutlass/blob/5b76420d6ae0ec0dbf82dc19317890551bffb1a6/include/cute/atom/copy_atom.hpp#L270
would collapse the thread modes but keep the val modes separate, which is opposite to what the doc indicates.
Sending the PR mainly to confirm my understanding of the function logic. Thank you!
=> Fix incorrect shapes in copy_atom doc comments.

media/docs/cpp/cute/02_layout_algebra.md
``` cpp
auto l = make_layout(make_shape(3, 6, 2, 8), make_stride(96, 16, 8, 2));
auto p = make_layout(16_c, 72_c);
auto q = composition(l, p);
print(q);
```
output: 
(3,6,2,8):(96,16,8,2)
_16:_72
(1,1,1,16):(6912,384,32,4)
`(3,6,2,8):(96,16,8,2) / 72` produces `(96*72, 16*24, 8*4, 2*2)` as the strides of the strided layout, not `(96*3, 16*6, 8*2, 2*2)`
=> Fix: a calculation error in the example of dividing out in the 02_layout_algebra doc

include/cutlass/bfloat16.h
How described at https://en.cppreference.com/w/cpp/types/numeric_limits/epsilon.html
numeric_limits::epsilon should return machine epsilon, and for bfloat16 might be represented as committed.
Current constant 0x1000 has nothing in common with this machine epsilon.
=> Fix bfloat16 epsilon
